#! /usr/bin/env nix-shell
#! nix-shell -i ruby
#! nix-shell -p ruby cabal2nix

# Take those from https://github.com/elm-lang/elm-platform/blob/master/installers/BuildFromSource.hs
elm_version = '0.17.1'
elm_packages = %w(elm-compiler elm-package elm-make elm-reactor elm-repl)

elm_packages.each do |pkg|
  system "cabal2nix https://github.com/elm-lang/#{pkg} --revision refs/tags/#{elm_version} --jailbreak > packages/#{pkg}.nix"
end

File.open("packages/release.nix", 'w') do |file|
  file.puts "# This file is auto-generated by ./update-elm.rb."
  file.puts "# Please, do not modify it by hand!"
  file.puts "{ callPackage }:"
  file.puts "{"
  file.puts "  version = \"#{elm_version}\";"
  file.puts "  packages = {"
  elm_packages.each do |pkg|
    file.puts "    #{pkg} = callPackage ./#{pkg}.nix { };"
  end
  file.puts "  };"
  file.puts "}"
end
