#!/usr/bin/env nix-shell
#!nix-shell -i ruby
#!nix-shell -p ruby
#!nix-shell -p cabal2nix

# Take those from https://github.com/elm-lang/elm-platform/blob/master/installers/BuildFromSource.hs
VERSION = "0.18.0"
PACKAGES = %w(elm-compiler elm-package elm-make elm-reactor elm-repl)

PACKAGES.each do |pkg|
  system "cabal2nix https://github.com/elm-lang/#{pkg} --revision refs/tags/#{VERSION} --jailbreak > packages/#{pkg}.nix"
end

File.open("packages/release.nix", 'w') do |file|
  file.puts %Q|
# This file is auto-generated by ./update-elm.rb.
# Please, do not modify it by hand!
{ callPackage }:
{
  version = "#{VERSION}"
  packages = {
  #{PACKAGES.each { |pkg| "    #{pkg} = callPackage ./#{pkg}.nix { };"}
  };
}
|
end
