# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/aws/aws-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/aws/aws-sdk-go";
      rev = "b66133bf477542f3e131668aa439e50f4cb47b2e";
      sha256 = "1ljvdhgsk1zwardcyiwcy9qzb5ihsp7hrsgwjphv9j01cjr8zgmk";
    };
  }
  {
    goPackagePath = "github.com/bgentry/go-netrc";
    fetch = {
      type = "git";
      url = "https://github.com/bgentry/go-netrc";
      rev = "9fd32a8b3d3d3f9d43c341bfe098430e07609480";
      sha256 = "0dn2h8avgavqdzdqnph8bkhj35bx0wssczry1zdczr22xv650g1l";
    };
  }
  {
    goPackagePath = "github.com/go-errors/errors";
    fetch = {
      type = "git";
      url = "https://github.com/go-errors/errors";
      rev = "a6af135bd4e28680facf08a3d206b454abc877a4";
      sha256 = "0rznpknk19rxkr7li6dqs52c26pjazp69lh493l4ny4sxn5922lp";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-cleanhttp";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-cleanhttp";
      rev = "d5fe4b57a186c716b0e00b8c301cbd9b4182694d";
      sha256 = "1m20y90syky4xr81sm3980jpil81nnpzmi6kv0vjr6p584gl1hn8";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-getter";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-getter";
      rev = "3f60ec5cfbb2a39731571b9ddae54b303bb0a969";
      sha256 = "13g15zmfgg4x94nqgc90yimk2ws8qbfzbmys6rl44awndhpwyh60";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-safetemp";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-safetemp";
      rev = "b1a1dbde6fdc11e3ae79efd9039009e22d4ae240";
      sha256 = "0r8p9g2zmayb297bcs5hrxnnqj4p5qda29w1a1rmq6hi26shz1gy";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-version";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-version";
      rev = "23480c0665776210b5fbbac6eaaee40e3e6a96b7";
      sha256 = "056zs67diq3m7skmmq3pnz6wymfcg55dfs5zf86xkfqqpj10kyf7";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/hcl";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/hcl";
      rev = "ef8a98b0bbce4a65b5aa4c368430a80ddc533168";
      sha256 = "1qalfsc31fra7hcw2lc3s20aj7al62fq3j5fn5kga3mg99b82nyr";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-zglob";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-zglob";
      rev = "9960a25705902198f55789b9b689a686682798b5";
      sha256 = "1awm9sgxbazniivwwfscpls90kv8nydd1lxfnx5881945bijdsjg";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "b8bc1bf767474819792c23f32d8286a45736f1c6";
      sha256 = "13ry4lylalkh4g2vny9cxwvryslzyzwp9r92z0b10idhdq3wad1q";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-testing-interface";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-testing-interface";
      rev = "a61a99592b77c9ba629d254a693acffaeb4b7e28";
      sha256 = "139hq835jpgk9pjg94br9d08nka8bfm7zyw92zxlwrkska4pgigx";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/mapstructure";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/mapstructure";
      rev = "00c29f56e2386353d58c599509e8dc3801b0d716";
      sha256 = "1vw8fvhax0d567amgvxr7glcl12lvzg2sbzs007q5k5bbwn1szyb";
    };
  }
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "c679ae2cc0cb27ec3293fea7e254e47386f05d69";
      sha256 = "1rrdn7k83j492rzhqwkh6956sj8m2nbk44d7r1xa9nsn3hfwj691";
    };
  }
  {
    goPackagePath = "github.com/ulikunitz/xz";
    fetch = {
      type = "git";
      url = "https://github.com/ulikunitz/xz";
      rev = "0c6b41e72360850ca4f98dc341fd999726ea007f";
      sha256 = "0a6l7sp67ipxim093qh6fvw8knbxj24l7bj5lykcddi5gwfi78n3";
    };
  }
  {
    goPackagePath = "github.com/urfave/cli";
    fetch = {
      type = "git";
      url = "https://github.com/urfave/cli";
      rev = "8e01ec4cd3e2d84ab2fe90d8210528ffbb06d8ff";
      sha256 = "0cpr10n4ps3gcdbcink71ry9hzhdb5rrcysmylybs8h2lzxqgc1i";
    };
  }
]
