# This file has been generated by node2nix 1.2.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "bluebird-3.5.0" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.5.0.tgz";
        sha1 = "791420d7f551eea2897453a8a77653f96606d67c";
      };
    };
    "request-promise-3.0.0" = {
      name = "request-promise";
      packageName = "request-promise";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request-promise/-/request-promise-3.0.0.tgz";
        sha1 = "be1edb26f41c49cd1d5656c6753d6842a1249f46";
      };
    };
    "matrix-appservice-bridge-git://github.com/matrix-org/matrix-appservice-bridge#ca40ff5" = {
      name = "matrix-appservice-bridge";
      packageName = "matrix-appservice-bridge";
      version = "1.3.3";
      src = fetchgit {
        url = "git://github.com/matrix-org/matrix-appservice-bridge";
        rev = "ca40ff5d5b415c8fdc82127d4c9117a7048e124d";
        sha256 = "62f6485fd092433e0ac147b1830dc802d1143c7956b2506a66cffdbf8b0a6e4a";
      };
    };
    "matrix-js-sdk-0.5.6" = {
      name = "matrix-js-sdk";
      packageName = "matrix-js-sdk";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/matrix-js-sdk/-/matrix-js-sdk-0.5.6.tgz";
        sha1 = "4cb4e01c507a4a07b575328d05970b65d427c37b";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "randomstring-1.1.5" = {
      name = "randomstring";
      packageName = "randomstring";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomstring/-/randomstring-1.1.5.tgz";
        sha1 = "6df0628f75cbd5932930d9fe3ab4e956a18518c3";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "request-2.81.0" = {
      name = "request";
      packageName = "request";
      version = "2.81.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.81.0.tgz";
        sha1 = "c6928946a0e06c5f8d6f8a9333469ffda46298a0";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "aws4-1.6.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz";
        sha1 = "83ef5ca860b2b32e4a0deedee8c771b9db57471e";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "extend-3.0.0" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.0.tgz";
        sha1 = "5a474353b9f3353ddd8176dfd37b91c83a46f1d4";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.1.4" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.1.4.tgz";
        sha1 = "33c183acf193276ecaa98143a69e94bfee1750d1";
      };
    };
    "har-validator-4.2.1" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-4.2.1.tgz";
        sha1 = "33481d0f1bbff600dd203d75812a6a5fba002e2a";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "http-signature-1.1.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz";
        sha1 = "df72e267066cd0ac67fb76adf8e134a8fbcf91bf";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "mime-types-2.1.15" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.15.tgz";
        sha1 = "a4ebf5064094569237b8cf70046776d09fc92aed";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "performance-now-0.2.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-0.2.0.tgz";
        sha1 = "33ef30c5c77d4ea21c5a53869d91b56d8f2555e5";
      };
    };
    "qs-6.4.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.4.0.tgz";
        sha1 = "13e26d28ad6b0ffaa91312cd3bf708ed351e7233";
      };
    };
    "safe-buffer-5.0.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.0.1.tgz";
        sha1 = "d263ca54696cd8a306b5ca6551e92de57918fbe7";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.2" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.2.tgz";
        sha1 = "f081f76e4c85720e6c37a5faced737150d84072a";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "uuid-3.0.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.0.1.tgz";
        sha1 = "6544bba2dfda8c1cf17e629a3a305e2bb1fee6c1";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "ajv-4.11.7" = {
      name = "ajv";
      packageName = "ajv";
      version = "4.11.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-4.11.7.tgz";
        sha1 = "8655a5d86d0824985cc471a1d913fb6729a0ec48";
      };
    };
    "har-schema-1.0.5" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-1.0.5.tgz";
        sha1 = "d263135f43307c02c602afc8fe95970c0151369e";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "json-stable-stringify-1.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-1.0.1.tgz";
        sha1 = "9a759d39c5f2ff503fd5300646ed445f88c4f9af";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "assert-plus-0.2.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.2.0.tgz";
        sha1 = "d74e1b87e7affc0db8aadb7021f3fe48101ab234";
      };
    };
    "jsprim-1.4.0" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.0.tgz";
        sha1 = "a3b87e40298d8c380552d8cc7628a0bb95a22918";
      };
    };
    "sshpk-1.13.0" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.13.0.tgz";
        sha1 = "ff2a3e4fd04497555fed97b39a0fd82fafb3a33c";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "extsprintf-1.0.2" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.0.2.tgz";
        sha1 = "e1080e0658e300b06294990cc70e1502235fd550";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "verror-1.3.6" = {
      name = "verror";
      packageName = "verror";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.3.6.tgz";
        sha1 = "cff5df12946d297d2baaefaa2689e25be01c005c";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "getpass-0.1.6" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.6.tgz";
        sha1 = "283ffd9fc1256840875311c1b60e8c40187110e6";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "jodid25519-1.0.2" = {
      name = "jodid25519";
      packageName = "jodid25519";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jodid25519/-/jodid25519-1.0.2.tgz";
        sha1 = "06d4912255093419477d425633606e0e90782967";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "mime-db-1.27.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.27.0.tgz";
        sha1 = "820f572296bbd20ec25ed55e5b5de869e5436eb1";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "bluebird-2.11.0" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-2.11.0.tgz";
        sha1 = "534b9033c022c9579c56ba3b3e5a5caafbb650e1";
      };
    };
    "jayschema-0.3.1" = {
      name = "jayschema";
      packageName = "jayschema";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jayschema/-/jayschema-0.3.1.tgz";
        sha1 = "76f4769f9b172ef7d5dcde4875b49cb736179b58";
      };
    };
    "js-yaml-3.8.3" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.8.3.tgz";
        sha1 = "33a05ec481c850c8875929166fe1beb61c728766";
      };
    };
    "matrix-appservice-0.3.3" = {
      name = "matrix-appservice";
      packageName = "matrix-appservice";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/matrix-appservice/-/matrix-appservice-0.3.3.tgz";
        sha1 = "b062ff21dcc33df107b18af29dcf8b41a6c50d71";
      };
    };
    "matrix-js-sdk-0.5.3" = {
      name = "matrix-js-sdk";
      packageName = "matrix-js-sdk";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/matrix-js-sdk/-/matrix-js-sdk-0.5.3.tgz";
        sha1 = "dbccd3aa007464a0475d53a2e39169b050dce247";
      };
    };
    "nedb-1.8.0" = {
      name = "nedb";
      packageName = "nedb";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nedb/-/nedb-1.8.0.tgz";
        sha1 = "0e3502cd82c004d5355a43c9e55577bd7bd91d88";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "when-3.4.6" = {
      name = "when";
      packageName = "when";
      version = "3.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/when/-/when-3.4.6.tgz";
        sha1 = "8fbcb7cc1439d2c3a68c431f1516e6dcce9ad28c";
      };
    };
    "argparse-1.0.9" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.9.tgz";
        sha1 = "73d83bc263f86e97f8cc4f6bae1b0e90a7d22c86";
      };
    };
    "esprima-3.1.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-3.1.3.tgz";
        sha1 = "fdca51cee6133895e3c88d535ce49dbff62a4633";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "body-parser-1.12.4" = {
      name = "body-parser";
      packageName = "body-parser";
      version = "1.12.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/body-parser/-/body-parser-1.12.4.tgz";
        sha1 = "090700c4ba28862a8520ef378395fdee5f61c229";
      };
    };
    "express-4.12.4" = {
      name = "express";
      packageName = "express";
      version = "4.12.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-4.12.4.tgz";
        sha1 = "8fec2510255bc6b2e58107c48239c0fa307c1aa2";
      };
    };
    "morgan-1.5.3" = {
      name = "morgan";
      packageName = "morgan";
      version = "1.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/morgan/-/morgan-1.5.3.tgz";
        sha1 = "8adb4e72f9e5c5436e5d93f42910835f79da9fdf";
      };
    };
    "request-2.53.0" = {
      name = "request";
      packageName = "request";
      version = "2.53.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.53.0.tgz";
        sha1 = "180a3ae92b7b639802e4f9545dd8fcdeb71d760c";
      };
    };
    "bytes-1.0.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-1.0.0.tgz";
        sha1 = "3569ede8ba34315fab99c3e92cb04c7220de1fa8";
      };
    };
    "content-type-1.0.2" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.2.tgz";
        sha1 = "b7d113aee7a8dd27bd21133c4dc2529df1721eed";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "depd-1.0.1" = {
      name = "depd";
      packageName = "depd";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.0.1.tgz";
        sha1 = "80aec64c9d6d97e65cc2a9caa93c0aa6abf73aaa";
      };
    };
    "iconv-lite-0.4.8" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.8.tgz";
        sha1 = "c6019a7595f2cefca702eab694a010bcd9298d20";
      };
    };
    "on-finished-2.2.1" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.2.1.tgz";
        sha1 = "5c85c1cc36299f78029653f667f27b6b99ebc029";
      };
    };
    "qs-2.4.2" = {
      name = "qs";
      packageName = "qs";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-2.4.2.tgz";
        sha1 = "f7ce788e5777df0b5010da7f7c4e73ba32470f5a";
      };
    };
    "raw-body-2.0.2" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.0.2.tgz";
        sha1 = "a2c2f98c8531cee99c63d8d238b7de97bb659fca";
      };
    };
    "type-is-1.6.15" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.15.tgz";
        sha1 = "cab10fb4909e441c82842eafe1ad646c81804410";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "ee-first-1.1.0" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.0.tgz";
        sha1 = "6a0d7c6221e490feefd92ec3f441c9ce8cd097f4";
      };
    };
    "bytes-2.1.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-2.1.0.tgz";
        sha1 = "ac93c410e2ffc9cc7cf4b464b38289067f5e47b4";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "accepts-1.2.13" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.2.13.tgz";
        sha1 = "e5f1f3928c6d95fd96558c36ec3d9d0de4a6ecea";
      };
    };
    "content-disposition-0.5.0" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.0.tgz";
        sha1 = "4284fe6ae0630874639e44e80a418c2934135e9e";
      };
    };
    "cookie-0.1.2" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.1.2.tgz";
        sha1 = "72fec3d24e48a3432073d90c12642005061004b1";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "escape-html-1.0.1" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.1.tgz";
        sha1 = "181a286ead397a39a92857cfb1d43052e356bff0";
      };
    };
    "etag-1.6.0" = {
      name = "etag";
      packageName = "etag";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.6.0.tgz";
        sha1 = "8bcb2c6af1254c481dfc8b997c906ef4e442c207";
      };
    };
    "finalhandler-0.3.6" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-0.3.6.tgz";
        sha1 = "daf9c4161b1b06e001466b1411dfdb6973be138b";
      };
    };
    "fresh-0.2.4" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.2.4.tgz";
        sha1 = "3582499206c9723714190edd74b4604feb4a614c";
      };
    };
    "merge-descriptors-1.0.0" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.0.tgz";
        sha1 = "2169cf7538e1b0cc87fb88e1502d8474bbf79864";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "parseurl-1.3.1" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz";
        sha1 = "c8ab8c9223ba34888aa64a297b28853bec18da56";
      };
    };
    "path-to-regexp-0.1.3" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.3.tgz";
        sha1 = "21b9ab82274279de25b156ea08fd12ca51b8aecb";
      };
    };
    "proxy-addr-1.0.10" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.0.10.tgz";
        sha1 = "0d40a82f801fc355567d2ecb65efe3f077f121c5";
      };
    };
    "range-parser-1.0.3" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.0.3.tgz";
        sha1 = "6872823535c692e2c2a0103826afd82c2e0ff175";
      };
    };
    "send-0.12.3" = {
      name = "send";
      packageName = "send";
      version = "0.12.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.12.3.tgz";
        sha1 = "cd12dc58fde21e4f91902b39b2fda05a7a6d9bdc";
      };
    };
    "serve-static-1.9.3" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.9.3.tgz";
        sha1 = "5f8da07323ad385ff3dc541f1a7917b2e436eb57";
      };
    };
    "vary-1.0.1" = {
      name = "vary";
      packageName = "vary";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.0.1.tgz";
        sha1 = "99e4981566a286118dfb2b817357df7993376d10";
      };
    };
    "utils-merge-1.0.0" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz";
        sha1 = "0294fb922bb9375153541c4f7096231f287c8af8";
      };
    };
    "negotiator-0.5.3" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.5.3.tgz";
        sha1 = "269d5c476810ec92edbe7b6c2f28316384f9a7e8";
      };
    };
    "crc-3.2.1" = {
      name = "crc";
      packageName = "crc";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/crc/-/crc-3.2.1.tgz";
        sha1 = "5d9c8fb77a245cd5eca291e5d2d005334bab0082";
      };
    };
    "forwarded-0.1.0" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.0.tgz";
        sha1 = "19ef9874c4ae1c297bcf078fde63a09b66a84363";
      };
    };
    "ipaddr.js-1.0.5" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.0.5.tgz";
        sha1 = "5fa78cf301b825c78abc3042d812723049ea23c7";
      };
    };
    "destroy-1.0.3" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.3.tgz";
        sha1 = "b433b4724e71fd8551d9885174851c5fc377e2c9";
      };
    };
    "mime-1.3.4" = {
      name = "mime";
      packageName = "mime";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.3.4.tgz";
        sha1 = "115f9e3b6b3daf2959983cb38f149a2d40eb5d53";
      };
    };
    "basic-auth-1.0.4" = {
      name = "basic-auth";
      packageName = "basic-auth";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/basic-auth/-/basic-auth-1.0.4.tgz";
        sha1 = "030935b01de7c9b94a824b29f3fccb750d3a5290";
      };
    };
    "bl-0.9.5" = {
      name = "bl";
      packageName = "bl";
      version = "0.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-0.9.5.tgz";
        sha1 = "c06b797af085ea00bc527afc8efcf11de2232054";
      };
    };
    "caseless-0.9.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.9.0.tgz";
        sha1 = "b7b65ce6bf1413886539cfd533f0b30effa9cf88";
      };
    };
    "forever-agent-0.5.2" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.5.2.tgz";
        sha1 = "6d0e09c4921f94a27f63d3b49c5feff1ea4c5130";
      };
    };
    "form-data-0.2.0" = {
      name = "form-data";
      packageName = "form-data";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-0.2.0.tgz";
        sha1 = "26f8bc26da6440e299cbdcfb69035c4f77a6e466";
      };
    };
    "mime-types-2.0.14" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.0.14.tgz";
        sha1 = "310e159db23e077f8bb22b748dabfa4957140aa6";
      };
    };
    "node-uuid-1.4.8" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.8.tgz";
        sha1 = "b040eb0923968afabf8d32fb1f17f1167fdab907";
      };
    };
    "qs-2.3.3" = {
      name = "qs";
      packageName = "qs";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-2.3.3.tgz";
        sha1 = "e9e85adbe75da0bbe4c8e0476a086290f863b404";
      };
    };
    "tunnel-agent-0.4.3" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.4.3.tgz";
        sha1 = "6373db76909fe570e08d73583365ed828a74eeeb";
      };
    };
    "http-signature-0.10.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "0.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-0.10.1.tgz";
        sha1 = "4fbdac132559aa8323121e540779c0a012b27e66";
      };
    };
    "oauth-sign-0.6.0" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.6.0.tgz";
        sha1 = "7dbeae44f6ca454e1f168451d630746735813ce3";
      };
    };
    "hawk-2.3.1" = {
      name = "hawk";
      packageName = "hawk";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-2.3.1.tgz";
        sha1 = "1e731ce39447fa1d0f6d707f7bceebec0fd1ec1f";
      };
    };
    "aws-sign2-0.5.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.5.0.tgz";
        sha1 = "c57103f7a17fc037f02d7c2e64b602ea223f7d63";
      };
    };
    "combined-stream-0.0.7" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-0.0.7.tgz";
        sha1 = "0137e657baa5a7541c57ac37ac5fc07d73b4dc1f";
      };
    };
    "readable-stream-1.0.34" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.0.34";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz";
        sha1 = "125820e34bc842d2f2aaafafe4c2916ee32c157c";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "async-0.9.2" = {
      name = "async";
      packageName = "async";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.9.2.tgz";
        sha1 = "aea74d5e61c1f899613bf64bda66d4c78f2fd17d";
      };
    };
    "mime-db-1.12.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.12.0.tgz";
        sha1 = "3d0c63180f458eb10d325aaa37d7c58ae312e9d7";
      };
    };
    "assert-plus-0.1.5" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.1.5.tgz";
        sha1 = "ee74009413002d84cec7219c6ac811812e723160";
      };
    };
    "asn1-0.1.11" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.1.11.tgz";
        sha1 = "559be18376d08a4ec4dbe80877d27818639b2df7";
      };
    };
    "ctype-0.5.3" = {
      name = "ctype";
      packageName = "ctype";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ctype/-/ctype-0.5.3.tgz";
        sha1 = "82c18c2461f74114ef16c135224ad0b9144ca12f";
      };
    };
    "delayed-stream-0.0.5" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-0.0.5.tgz";
        sha1 = "d4b1f43a93e8296dfe02694f4680bc37a313c73f";
      };
    };
    "browser-request-0.3.3" = {
      name = "browser-request";
      packageName = "browser-request";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-request/-/browser-request-0.3.3.tgz";
        sha1 = "9ece5b5aca89a29932242e18bf933def9876cc17";
      };
    };
    "browserify-10.2.6" = {
      name = "browserify";
      packageName = "browserify";
      version = "10.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify/-/browserify-10.2.6.tgz";
        sha1 = "dcbfef794f548f5f8498214814f697a5c50c0896";
      };
    };
    "q-1.5.0" = {
      name = "q";
      packageName = "q";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/q/-/q-1.5.0.tgz";
        sha1 = "dd01bac9d06d30e6f219aecb8253ee9ebdc308f1";
      };
    };
    "JSONStream-1.3.1" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-1.3.1.tgz";
        sha1 = "707f761e01dae9e16f1bcf93703b78c70966579a";
      };
    };
    "assert-1.3.0" = {
      name = "assert";
      packageName = "assert";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert/-/assert-1.3.0.tgz";
        sha1 = "03939a622582a812cc202320a0b9a56c9b815849";
      };
    };
    "browser-pack-5.0.1" = {
      name = "browser-pack";
      packageName = "browser-pack";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-pack/-/browser-pack-5.0.1.tgz";
        sha1 = "4197719b20c6e0aaa09451c5111e53efb6fbc18d";
      };
    };
    "browser-resolve-1.11.2" = {
      name = "browser-resolve";
      packageName = "browser-resolve";
      version = "1.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-resolve/-/browser-resolve-1.11.2.tgz";
        sha1 = "8ff09b0a2c421718a1051c260b32e48f442938ce";
      };
    };
    "browserify-zlib-0.1.4" = {
      name = "browserify-zlib";
      packageName = "browserify-zlib";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-zlib/-/browserify-zlib-0.1.4.tgz";
        sha1 = "bb35f8a519f600e0fa6b8485241c979d0141fb2d";
      };
    };
    "buffer-3.6.0" = {
      name = "buffer";
      packageName = "buffer";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-3.6.0.tgz";
        sha1 = "a72c936f77b96bf52f5f7e7b467180628551defb";
      };
    };
    "builtins-0.0.7" = {
      name = "builtins";
      packageName = "builtins";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtins/-/builtins-0.0.7.tgz";
        sha1 = "355219cd6cf18dbe7c01cc7fd2dce765cfdc549a";
      };
    };
    "commondir-0.0.1" = {
      name = "commondir";
      packageName = "commondir";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commondir/-/commondir-0.0.1.tgz";
        sha1 = "89f00fdcd51b519c578733fec563e6a6da7f5be2";
      };
    };
    "concat-stream-1.4.10" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.4.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.4.10.tgz";
        sha1 = "acc3bbf5602cb8cc980c6ac840fa7d8603e3ef36";
      };
    };
    "console-browserify-1.1.0" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-browserify/-/console-browserify-1.1.0.tgz";
        sha1 = "f0241c45730a9fc6323b206dbf38edc741d0bb10";
      };
    };
    "constants-browserify-0.0.1" = {
      name = "constants-browserify";
      packageName = "constants-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/constants-browserify/-/constants-browserify-0.0.1.tgz";
        sha1 = "92577db527ba6c4cf0a4568d84bc031f441e21f2";
      };
    };
    "crypto-browserify-3.11.0" = {
      name = "crypto-browserify";
      packageName = "crypto-browserify";
      version = "3.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-3.11.0.tgz";
        sha1 = "3652a0906ab9b2a7e0c3ce66a408e957a2485522";
      };
    };
    "defined-1.0.0" = {
      name = "defined";
      packageName = "defined";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/defined/-/defined-1.0.0.tgz";
        sha1 = "c98d9bcef75674188e110969151199e39b1fa693";
      };
    };
    "deps-sort-1.3.9" = {
      name = "deps-sort";
      packageName = "deps-sort";
      version = "1.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/deps-sort/-/deps-sort-1.3.9.tgz";
        sha1 = "29dfff53e17b36aecae7530adbbbf622c2ed1a71";
      };
    };
    "domain-browser-1.1.7" = {
      name = "domain-browser";
      packageName = "domain-browser";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/domain-browser/-/domain-browser-1.1.7.tgz";
        sha1 = "867aa4b093faa05f1de08c06f4d7b21fdf8698bc";
      };
    };
    "duplexer2-0.0.2" = {
      name = "duplexer2";
      packageName = "duplexer2";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer2/-/duplexer2-0.0.2.tgz";
        sha1 = "c614dcf67e2fb14995a91711e5a617e8a60a31db";
      };
    };
    "events-1.0.2" = {
      name = "events";
      packageName = "events";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-1.0.2.tgz";
        sha1 = "75849dcfe93d10fb057c30055afdbd51d06a8e24";
      };
    };
    "glob-4.5.3" = {
      name = "glob";
      packageName = "glob";
      version = "4.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-4.5.3.tgz";
        sha1 = "c6cb73d3226c1efef04de3c56d012f03377ee15f";
      };
    };
    "has-1.0.1" = {
      name = "has";
      packageName = "has";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.1.tgz";
        sha1 = "8461733f538b0837c9361e39a9ab9e9704dc2f28";
      };
    };
    "htmlescape-1.1.1" = {
      name = "htmlescape";
      packageName = "htmlescape";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlescape/-/htmlescape-1.1.1.tgz";
        sha1 = "3a03edc2214bca3b66424a3e7959349509cb0351";
      };
    };
    "http-browserify-1.7.0" = {
      name = "http-browserify";
      packageName = "http-browserify";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-browserify/-/http-browserify-1.7.0.tgz";
        sha1 = "33795ade72df88acfbfd36773cefeda764735b20";
      };
    };
    "https-browserify-0.0.1" = {
      name = "https-browserify";
      packageName = "https-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-browserify/-/https-browserify-0.0.1.tgz";
        sha1 = "3f91365cabe60b77ed0ebba24b454e3e09d95a82";
      };
    };
    "insert-module-globals-6.6.3" = {
      name = "insert-module-globals";
      packageName = "insert-module-globals";
      version = "6.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/insert-module-globals/-/insert-module-globals-6.6.3.tgz";
        sha1 = "20638e29a30f9ed1ca2e3a825fbc2cba5246ddfc";
      };
    };
    "labeled-stream-splicer-1.0.2" = {
      name = "labeled-stream-splicer";
      packageName = "labeled-stream-splicer";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/labeled-stream-splicer/-/labeled-stream-splicer-1.0.2.tgz";
        sha1 = "4615331537784981e8fd264e1f3a434c4e0ddd65";
      };
    };
    "module-deps-3.9.1" = {
      name = "module-deps";
      packageName = "module-deps";
      version = "3.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/module-deps/-/module-deps-3.9.1.tgz";
        sha1 = "ea75caf9199090d25b0d5512b5acacb96e7f87f3";
      };
    };
    "os-browserify-0.1.2" = {
      name = "os-browserify";
      packageName = "os-browserify";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-browserify/-/os-browserify-0.1.2.tgz";
        sha1 = "49ca0293e0b19590a5f5de10c7f265a617d8fe54";
      };
    };
    "parents-1.0.1" = {
      name = "parents";
      packageName = "parents";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parents/-/parents-1.0.1.tgz";
        sha1 = "fedd4d2bf193a77745fe71e371d73c3307d9c751";
      };
    };
    "path-browserify-0.0.0" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-browserify/-/path-browserify-0.0.0.tgz";
        sha1 = "a0b870729aae214005b7d5032ec2cbbb0fb4451a";
      };
    };
    "process-0.11.9" = {
      name = "process";
      packageName = "process";
      version = "0.11.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.9.tgz";
        sha1 = "7bd5ad21aa6253e7da8682264f1e11d11c0318c1";
      };
    };
    "querystring-es3-0.2.1" = {
      name = "querystring-es3";
      packageName = "querystring-es3";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring-es3/-/querystring-es3-0.2.1.tgz";
        sha1 = "9ec61f79049875707d69414596fd907a4d711e73";
      };
    };
    "read-only-stream-1.1.1" = {
      name = "read-only-stream";
      packageName = "read-only-stream";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-only-stream/-/read-only-stream-1.1.1.tgz";
        sha1 = "5da77c799ed1388d3ef88a18471bb5924f8a0ba1";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "resolve-1.3.2" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.3.2.tgz";
        sha1 = "1f0442c9e0cbb8136e87b9305f932f46c7f28235";
      };
    };
    "shasum-1.0.2" = {
      name = "shasum";
      packageName = "shasum";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shasum/-/shasum-1.0.2.tgz";
        sha1 = "e7012310d8f417f4deb5712150e5678b87ae565f";
      };
    };
    "shell-quote-0.0.1" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-0.0.1.tgz";
        sha1 = "1a41196f3c0333c482323593d6886ecf153dd986";
      };
    };
    "stream-browserify-1.0.0" = {
      name = "stream-browserify";
      packageName = "stream-browserify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-browserify/-/stream-browserify-1.0.0.tgz";
        sha1 = "bf9b4abfb42b274d751479e44e0ff2656b6f1193";
      };
    };
    "subarg-1.0.0" = {
      name = "subarg";
      packageName = "subarg";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/subarg/-/subarg-1.0.0.tgz";
        sha1 = "f62cf17581e996b48fc965699f54c06ae268b8d2";
      };
    };
    "syntax-error-1.3.0" = {
      name = "syntax-error";
      packageName = "syntax-error";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/syntax-error/-/syntax-error-1.3.0.tgz";
        sha1 = "1ed9266c4d40be75dc55bf9bb1cb77062bb96ca1";
      };
    };
    "through2-1.1.1" = {
      name = "through2";
      packageName = "through2";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-1.1.1.tgz";
        sha1 = "0847cbc4449f3405574dbdccd9bb841b83ac3545";
      };
    };
    "timers-browserify-1.4.2" = {
      name = "timers-browserify";
      packageName = "timers-browserify";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/timers-browserify/-/timers-browserify-1.4.2.tgz";
        sha1 = "c9c58b575be8407375cb5e2462dacee74359f41d";
      };
    };
    "tty-browserify-0.0.0" = {
      name = "tty-browserify";
      packageName = "tty-browserify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tty-browserify/-/tty-browserify-0.0.0.tgz";
        sha1 = "a157ba402da24e9bf957f9aa69d524eed42901a6";
      };
    };
    "url-0.10.3" = {
      name = "url";
      packageName = "url";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/url/-/url-0.10.3.tgz";
        sha1 = "021e4d9c7705f21bbf37d03ceb58767402774c64";
      };
    };
    "util-0.10.3" = {
      name = "util";
      packageName = "util";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.3.tgz";
        sha1 = "7afb1afe50805246489e3db7fe0ed379336ac0f9";
      };
    };
    "vm-browserify-0.0.4" = {
      name = "vm-browserify";
      packageName = "vm-browserify";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vm-browserify/-/vm-browserify-0.0.4.tgz";
        sha1 = "5d7ea45bbef9e4a6ff65f95438e0a87c357d5a73";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "jsonparse-1.3.0" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-1.3.0.tgz";
        sha1 = "85fc245b1d9259acc6941960b905adf64e7de0e8";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "combine-source-map-0.6.1" = {
      name = "combine-source-map";
      packageName = "combine-source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/combine-source-map/-/combine-source-map-0.6.1.tgz";
        sha1 = "9b4a09c316033d768e0f11e029fa2730e079ad96";
      };
    };
    "umd-3.0.1" = {
      name = "umd";
      packageName = "umd";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/umd/-/umd-3.0.1.tgz";
        sha1 = "8ae556e11011f63c2596708a8837259f01b3d60e";
      };
    };
    "convert-source-map-1.1.3" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.1.3.tgz";
        sha1 = "4829c877e9fe49b3161f3bf3673888e204699860";
      };
    };
    "inline-source-map-0.5.0" = {
      name = "inline-source-map";
      packageName = "inline-source-map";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-source-map/-/inline-source-map-0.5.0.tgz";
        sha1 = "4a4c5dd8e4fb5e9b3cda60c822dfadcaee66e0af";
      };
    };
    "lodash.memoize-3.0.4" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-3.0.4.tgz";
        sha1 = "2dcbd2c287cbc0a55cc42328bd0c736150d53e3f";
      };
    };
    "source-map-0.4.4" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.4.4.tgz";
        sha1 = "eba4f5da9c0dc999de68032d8b4f76173652036b";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha1 = "4a5282ac164729e93619bcfd3ad151f817ce91f5";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
    "pako-0.2.9" = {
      name = "pako";
      packageName = "pako";
      version = "0.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-0.2.9.tgz";
        sha1 = "f3f7522f4ef782348da8161bad9ecfd51bf83a75";
      };
    };
    "base64-js-0.0.8" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-0.0.8.tgz";
        sha1 = "1101e9544f4a76b1bc3b26d452ca96d7a35e7978";
      };
    };
    "ieee754-1.1.8" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.8.tgz";
        sha1 = "be33d40ac10ef1926701f6f08a2d86fbfd1ad3e4";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "date-now-0.1.4" = {
      name = "date-now";
      packageName = "date-now";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/date-now/-/date-now-0.1.4.tgz";
        sha1 = "eaf439fd4d4848ad74e5cc7dbef200672b9e345b";
      };
    };
    "browserify-cipher-1.0.0" = {
      name = "browserify-cipher";
      packageName = "browserify-cipher";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-cipher/-/browserify-cipher-1.0.0.tgz";
        sha1 = "9988244874bf5ed4e28da95666dcd66ac8fc363a";
      };
    };
    "browserify-sign-4.0.4" = {
      name = "browserify-sign";
      packageName = "browserify-sign";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-sign/-/browserify-sign-4.0.4.tgz";
        sha1 = "aa4eb68e5d7b658baa6bf6a57e630cbd7a93d298";
      };
    };
    "create-ecdh-4.0.0" = {
      name = "create-ecdh";
      packageName = "create-ecdh";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-ecdh/-/create-ecdh-4.0.0.tgz";
        sha1 = "888c723596cdf7612f6498233eebd7a35301737d";
      };
    };
    "create-hash-1.1.2" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.1.2.tgz";
        sha1 = "51210062d7bb7479f6c65bb41a92208b1d61abad";
      };
    };
    "create-hmac-1.1.4" = {
      name = "create-hmac";
      packageName = "create-hmac";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hmac/-/create-hmac-1.1.4.tgz";
        sha1 = "d3fb4ba253eb8b3f56e39ea2fbcb8af747bd3170";
      };
    };
    "diffie-hellman-5.0.2" = {
      name = "diffie-hellman";
      packageName = "diffie-hellman";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/diffie-hellman/-/diffie-hellman-5.0.2.tgz";
        sha1 = "b5835739270cfe26acf632099fded2a07f209e5e";
      };
    };
    "pbkdf2-3.0.9" = {
      name = "pbkdf2";
      packageName = "pbkdf2";
      version = "3.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/pbkdf2/-/pbkdf2-3.0.9.tgz";
        sha1 = "f2c4b25a600058b3c3773c086c37dbbee1ffe693";
      };
    };
    "public-encrypt-4.0.0" = {
      name = "public-encrypt";
      packageName = "public-encrypt";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/public-encrypt/-/public-encrypt-4.0.0.tgz";
        sha1 = "39f699f3a46560dd5ebacbca693caf7c65c18cc6";
      };
    };
    "randombytes-2.0.3" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.0.3.tgz";
        sha1 = "674c99760901c3c4112771a31e521dc349cc09ec";
      };
    };
    "browserify-aes-1.0.6" = {
      name = "browserify-aes";
      packageName = "browserify-aes";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-aes/-/browserify-aes-1.0.6.tgz";
        sha1 = "5e7725dbdef1fd5930d4ebab48567ce451c48a0a";
      };
    };
    "browserify-des-1.0.0" = {
      name = "browserify-des";
      packageName = "browserify-des";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-des/-/browserify-des-1.0.0.tgz";
        sha1 = "daa277717470922ed2fe18594118a175439721dd";
      };
    };
    "evp_bytestokey-1.0.0" = {
      name = "evp_bytestokey";
      packageName = "evp_bytestokey";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/evp_bytestokey/-/evp_bytestokey-1.0.0.tgz";
        sha1 = "497b66ad9fef65cd7c08a6180824ba1476b66e53";
      };
    };
    "buffer-xor-1.0.3" = {
      name = "buffer-xor";
      packageName = "buffer-xor";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-xor/-/buffer-xor-1.0.3.tgz";
        sha1 = "26e61ed1422fb70dd42e6e36729ed51d855fe8d9";
      };
    };
    "cipher-base-1.0.3" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.3.tgz";
        sha1 = "eeabf194419ce900da3018c207d212f2a6df0a07";
      };
    };
    "des.js-1.0.0" = {
      name = "des.js";
      packageName = "des.js";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/des.js/-/des.js-1.0.0.tgz";
        sha1 = "c074d2e2aa6a8a9a07dbd61f9a15c2cd83ec8ecc";
      };
    };
    "minimalistic-assert-1.0.0" = {
      name = "minimalistic-assert";
      packageName = "minimalistic-assert";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.0.tgz";
        sha1 = "702be2dda6b37f4836bcb3f5db56641b64a1d3d3";
      };
    };
    "bn.js-4.11.6" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "4.11.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-4.11.6.tgz";
        sha1 = "53344adb14617a13f6e8dd2ce28905d1c0ba3215";
      };
    };
    "browserify-rsa-4.0.1" = {
      name = "browserify-rsa";
      packageName = "browserify-rsa";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-rsa/-/browserify-rsa-4.0.1.tgz";
        sha1 = "21e0abfaf6f2029cf2fafb133567a701d4135524";
      };
    };
    "elliptic-6.4.0" = {
      name = "elliptic";
      packageName = "elliptic";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/elliptic/-/elliptic-6.4.0.tgz";
        sha1 = "cac9af8762c85836187003c8dfe193e5e2eae5df";
      };
    };
    "parse-asn1-5.1.0" = {
      name = "parse-asn1";
      packageName = "parse-asn1";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-asn1/-/parse-asn1-5.1.0.tgz";
        sha1 = "37c4f9b7ed3ab65c74817b5f2480937fbf97c712";
      };
    };
    "brorand-1.1.0" = {
      name = "brorand";
      packageName = "brorand";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/brorand/-/brorand-1.1.0.tgz";
        sha1 = "12c25efe40a45e3c323eb8675a0a0ce57b22371f";
      };
    };
    "hash.js-1.0.3" = {
      name = "hash.js";
      packageName = "hash.js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash.js/-/hash.js-1.0.3.tgz";
        sha1 = "1332ff00156c0a0ffdd8236013d07b77a0451573";
      };
    };
    "hmac-drbg-1.0.1" = {
      name = "hmac-drbg";
      packageName = "hmac-drbg";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hmac-drbg/-/hmac-drbg-1.0.1.tgz";
        sha1 = "d2745701025a6c775a6c545793ed502fc0c649a1";
      };
    };
    "minimalistic-crypto-utils-1.0.1" = {
      name = "minimalistic-crypto-utils";
      packageName = "minimalistic-crypto-utils";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-crypto-utils/-/minimalistic-crypto-utils-1.0.1.tgz";
        sha1 = "f6c00c1c0b082246e5c4d99dfb8c7c083b2b582a";
      };
    };
    "asn1.js-4.9.1" = {
      name = "asn1.js";
      packageName = "asn1.js";
      version = "4.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1.js/-/asn1.js-4.9.1.tgz";
        sha1 = "48ba240b45a9280e94748990ba597d216617fd40";
      };
    };
    "ripemd160-1.0.1" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-1.0.1.tgz";
        sha1 = "93a4bbd4942bc574b69a8fa57c71de10ecca7d6e";
      };
    };
    "sha.js-2.4.8" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.8.tgz";
        sha1 = "37068c2c476b6baf402d14a49c67f597921f634f";
      };
    };
    "miller-rabin-4.0.0" = {
      name = "miller-rabin";
      packageName = "miller-rabin";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/miller-rabin/-/miller-rabin-4.0.0.tgz";
        sha1 = "4a62fb1d42933c05583982f4c716f6fb9e6c6d3d";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "minimatch-2.0.10" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "2.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-2.0.10.tgz";
        sha1 = "8d087c39c6b38c001b97fca7ce6d0e1e80afbac7";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.7" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.7.tgz";
        sha1 = "3effc3c50e000531fb720eaff80f0ae8ef23cf59";
      };
    };
    "balanced-match-0.4.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz";
        sha1 = "cb3f3e3c732dc0f01ee70b403f302e61d7709838";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "function-bind-1.1.0" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.0.tgz";
        sha1 = "16176714c801798e4e8f2cf7f7529467bb4a5771";
      };
    };
    "Base64-0.2.1" = {
      name = "Base64";
      packageName = "Base64";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/Base64/-/Base64-0.2.1.tgz";
        sha1 = "ba3a4230708e186705065e66babdd4c35cf60028";
      };
    };
    "is-buffer-1.1.5" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.5.tgz";
        sha1 = "1f3b26ef613b214b88cbca23cc6c01d87961eecc";
      };
    };
    "lexical-scope-1.2.0" = {
      name = "lexical-scope";
      packageName = "lexical-scope";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lexical-scope/-/lexical-scope-1.2.0.tgz";
        sha1 = "fcea5edc704a4b3a8796cdca419c3a0afaf22df4";
      };
    };
    "astw-2.2.0" = {
      name = "astw";
      packageName = "astw";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/astw/-/astw-2.2.0.tgz";
        sha1 = "7bd41784d32493987aeb239b6b4e1c57a873b917";
      };
    };
    "acorn-4.0.11" = {
      name = "acorn";
      packageName = "acorn";
      version = "4.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-4.0.11.tgz";
        sha1 = "edcda3bd937e7556410d42ed5860f67399c794c0";
      };
    };
    "stream-splicer-1.3.2" = {
      name = "stream-splicer";
      packageName = "stream-splicer";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-splicer/-/stream-splicer-1.3.2.tgz";
        sha1 = "3c0441be15b9bf4e226275e6dc83964745546661";
      };
    };
    "readable-wrap-1.0.0" = {
      name = "readable-wrap";
      packageName = "readable-wrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-wrap/-/readable-wrap-1.0.0.tgz";
        sha1 = "3b5a211c631e12303a54991c806c17e7ae206bff";
      };
    };
    "indexof-0.0.1" = {
      name = "indexof";
      packageName = "indexof";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/indexof/-/indexof-0.0.1.tgz";
        sha1 = "82dc336d232b9062179d05ab3293a66059fd435d";
      };
    };
    "detective-4.5.0" = {
      name = "detective";
      packageName = "detective";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detective/-/detective-4.5.0.tgz";
        sha1 = "6e5a8c6b26e6c7a254b1c6b6d7490d98ec91edd1";
      };
    };
    "stream-combiner2-1.0.2" = {
      name = "stream-combiner2";
      packageName = "stream-combiner2";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-combiner2/-/stream-combiner2-1.0.2.tgz";
        sha1 = "ba72a6b50cbfabfa950fc8bc87604bd01eb60671";
      };
    };
    "through2-0.5.1" = {
      name = "through2";
      packageName = "through2";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-0.5.1.tgz";
        sha1 = "dfdd012eb9c700e2323fd334f38ac622ab372da7";
      };
    };
    "xtend-3.0.0" = {
      name = "xtend";
      packageName = "xtend";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-3.0.0.tgz";
        sha1 = "5cce7407baf642cba7becda568111c493f59665a";
      };
    };
    "path-platform-0.11.15" = {
      name = "path-platform";
      packageName = "path-platform";
      version = "0.11.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-platform/-/path-platform-0.11.15.tgz";
        sha1 = "e864217f74c36850f0852b78dc7bf7d4a5721bf2";
      };
    };
    "path-parse-1.0.5" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.5.tgz";
        sha1 = "3c1adf871ea9cd6c9431b6ea2bd74a0ff055c4c1";
      };
    };
    "json-stable-stringify-0.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-0.0.1.tgz";
        sha1 = "611c23e814db375527df851193db59dd2af27f45";
      };
    };
    "punycode-1.3.2" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz";
        sha1 = "9653a036fb7c1ee42342f2325cceefea3926c48d";
      };
    };
    "querystring-0.2.0" = {
      name = "querystring";
      packageName = "querystring";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz";
        sha1 = "b209849203bb25df820da756e747005878521620";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "async-0.2.10" = {
      name = "async";
      packageName = "async";
      version = "0.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.2.10.tgz";
        sha1 = "b6bbe0b0674b9d719708ca38de8c237cb526c3d1";
      };
    };
    "binary-search-tree-0.2.5" = {
      name = "binary-search-tree";
      packageName = "binary-search-tree";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-search-tree/-/binary-search-tree-0.2.5.tgz";
        sha1 = "7dbb3b210fdca082450dad2334c304af39bdc784";
      };
    };
    "localforage-1.5.0" = {
      name = "localforage";
      packageName = "localforage";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/localforage/-/localforage-1.5.0.tgz";
        sha1 = "6b994e19b56611fa85df3992df397ac4ab66e815";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "underscore-1.4.4" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz";
        sha1 = "61a6a32010622afa07963bf325203cf12239d604";
      };
    };
    "lie-3.0.2" = {
      name = "lie";
      packageName = "lie";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lie/-/lie-3.0.2.tgz";
        sha1 = "ffda21d7bba26f377cad865d3649b2fc8ce39fea";
      };
    };
    "es3ify-0.1.4" = {
      name = "es3ify";
      packageName = "es3ify";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/es3ify/-/es3ify-0.1.4.tgz";
        sha1 = "ad9fa5df1ae34f3f31e1211b5818b2d51078dfd1";
      };
    };
    "immediate-3.0.6" = {
      name = "immediate";
      packageName = "immediate";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/immediate/-/immediate-3.0.6.tgz";
        sha1 = "9db1dbd0faf8de6fbe0f5dd5e56bb606280de69b";
      };
    };
    "inline-process-browser-1.0.0" = {
      name = "inline-process-browser";
      packageName = "inline-process-browser";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-process-browser/-/inline-process-browser-1.0.0.tgz";
        sha1 = "46a61b153dd3c9b1624b1a00626edb4f7f414f22";
      };
    };
    "unreachable-branch-transform-0.3.0" = {
      name = "unreachable-branch-transform";
      packageName = "unreachable-branch-transform";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unreachable-branch-transform/-/unreachable-branch-transform-0.3.0.tgz";
        sha1 = "d99cc4c6e746d264928845b611db54b0f3474caa";
      };
    };
    "esprima-fb-3001.1.0-dev-harmony-fb" = {
      name = "esprima-fb";
      packageName = "esprima-fb";
      version = "3001.1.0-dev-harmony-fb";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima-fb/-/esprima-fb-3001.0001.0000-dev-harmony-fb.tgz";
        sha1 = "b77d37abcd38ea0b77426bb8bc2922ce6b426411";
      };
    };
    "jstransform-3.0.0" = {
      name = "jstransform";
      packageName = "jstransform";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jstransform/-/jstransform-3.0.0.tgz";
        sha1 = "a2591ab6cee8d97bf3be830dbfa2313b87cd640b";
      };
    };
    "base62-0.1.1" = {
      name = "base62";
      packageName = "base62";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base62/-/base62-0.1.1.tgz";
        sha1 = "7b4174c2f94449753b11c2651c083da841a7b084";
      };
    };
    "source-map-0.1.31" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.1.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.1.31.tgz";
        sha1 = "9f704d0d69d9e138a81badf6ebb4fde33d151c61";
      };
    };
    "falafel-1.2.0" = {
      name = "falafel";
      packageName = "falafel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/falafel/-/falafel-1.2.0.tgz";
        sha1 = "c18d24ef5091174a497f318cd24b026a25cddab4";
      };
    };
    "through2-0.6.5" = {
      name = "through2";
      packageName = "through2";
      version = "0.6.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-0.6.5.tgz";
        sha1 = "41ab9c67b29d57209071410e1d7a7a968cd3ad48";
      };
    };
    "acorn-1.2.2" = {
      name = "acorn";
      packageName = "acorn";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-1.2.2.tgz";
        sha1 = "c8ce27de0acc76d896d2b1fad3df588d9e82f014";
      };
    };
    "foreach-2.0.5" = {
      name = "foreach";
      packageName = "foreach";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz";
        sha1 = "0bee005018aeb260d0a3af3ae658dd0136ec1b99";
      };
    };
    "object-keys-1.0.11" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.0.11.tgz";
        sha1 = "c54601778ad560f1142ce0e01bcca8b56d13426d";
      };
    };
    "esmangle-evaluator-1.0.1" = {
      name = "esmangle-evaluator";
      packageName = "esmangle-evaluator";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esmangle-evaluator/-/esmangle-evaluator-1.0.1.tgz";
        sha1 = "620d866ef4861b3311f75766d52a8572bb3c6336";
      };
    };
    "recast-0.10.43" = {
      name = "recast";
      packageName = "recast";
      version = "0.10.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/recast/-/recast-0.10.43.tgz";
        sha1 = "b95d50f6d60761a5f6252e15d80678168491ce7f";
      };
    };
    "esprima-fb-15001.1001.0-dev-harmony-fb" = {
      name = "esprima-fb";
      packageName = "esprima-fb";
      version = "15001.1001.0-dev-harmony-fb";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima-fb/-/esprima-fb-15001.1001.0-dev-harmony-fb.tgz";
        sha1 = "43beb57ec26e8cf237d3dd8b33e42533577f2659";
      };
    };
    "source-map-0.5.6" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz";
        sha1 = "75ce38f52bf0733c5a7f0c118d81334a2bb5f412";
      };
    };
    "private-0.1.7" = {
      name = "private";
      packageName = "private";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/private/-/private-0.1.7.tgz";
        sha1 = "68ce5e8a1ef0a23bb570cc28537b5332aba63ef1";
      };
    };
    "ast-types-0.8.15" = {
      name = "ast-types";
      packageName = "ast-types";
      version = "0.8.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/ast-types/-/ast-types-0.8.15.tgz";
        sha1 = "8eef0827f04dff0ec8857ba925abe3fea6194e52";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "abbrev-1.1.0" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.0.tgz";
        sha1 = "d0554c2256636e2f56e7c2e5ad183f859428d81f";
      };
    };
    "another-json-0.2.0" = {
      name = "another-json";
      packageName = "another-json";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/another-json/-/another-json-0.2.0.tgz";
        sha1 = "b5f4019c973b6dd5c6506a2d93469cb6d32aeedc";
      };
    };
    "olm-https://matrix.org/packages/npm/olm/olm-1.0.0.tgz" = {
      name = "olm";
      packageName = "olm";
      version = "1.0.0";
      src = fetchurl {
        name = "olm-1.0.0.tar.gz";
        url = https://matrix.org/packages/npm/olm/olm-1.0.0.tgz;
        sha256 = "aecd50f224dac2ada87f9107700cd9eda494fae7bc24e5475b10594a8d09f3ae";
      };
    };
    "array-uniq-1.0.2" = {
      name = "array-uniq";
      packageName = "array-uniq";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-uniq/-/array-uniq-1.0.2.tgz";
        sha1 = "5fcc373920775723cfd64d65c64bef53bf9eba6d";
      };
    };
  };
  args = {
    name = "matrix-appservice-slack";
    packageName = "matrix-appservice-slack";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      sources."bluebird-3.5.0"
      sources."request-promise-3.0.0"
      (sources."matrix-appservice-bridge-git://github.com/matrix-org/matrix-appservice-bridge#ca40ff5" // {
        dependencies = [
          sources."bluebird-2.11.0"
          sources."matrix-js-sdk-0.5.3"
        ];
      })
      sources."matrix-js-sdk-0.5.6"
      sources."minimist-1.2.0"
      sources."randomstring-1.1.5"
      sources."lodash-4.17.4"
      sources."request-2.81.0"
      sources."aws-sign2-0.6.0"
      sources."aws4-1.6.0"
      sources."caseless-0.12.0"
      sources."combined-stream-1.0.5"
      sources."extend-3.0.0"
      sources."forever-agent-0.6.1"
      sources."form-data-2.1.4"
      sources."har-validator-4.2.1"
      sources."hawk-3.1.3"
      sources."http-signature-1.1.1"
      sources."is-typedarray-1.0.0"
      sources."isstream-0.1.2"
      sources."json-stringify-safe-5.0.1"
      sources."mime-types-2.1.15"
      sources."oauth-sign-0.8.2"
      sources."performance-now-0.2.0"
      sources."qs-6.4.0"
      sources."safe-buffer-5.0.1"
      sources."stringstream-0.0.5"
      sources."tough-cookie-2.3.2"
      sources."tunnel-agent-0.6.0"
      sources."uuid-3.0.1"
      sources."delayed-stream-1.0.0"
      sources."asynckit-0.4.0"
      sources."ajv-4.11.7"
      sources."har-schema-1.0.5"
      sources."co-4.6.0"
      sources."json-stable-stringify-1.0.1"
      sources."jsonify-0.0.0"
      sources."hoek-2.16.3"
      sources."boom-2.10.1"
      sources."cryptiles-2.0.5"
      sources."sntp-1.0.9"
      sources."assert-plus-0.2.0"
      (sources."jsprim-1.4.0" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      (sources."sshpk-1.13.0" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."extsprintf-1.0.2"
      sources."json-schema-0.2.3"
      sources."verror-1.3.6"
      sources."asn1-0.2.3"
      (sources."dashdash-1.14.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      (sources."getpass-0.1.6" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."jsbn-0.1.1"
      sources."tweetnacl-0.14.5"
      sources."jodid25519-1.0.2"
      sources."ecc-jsbn-0.1.1"
      sources."bcrypt-pbkdf-1.0.1"
      sources."mime-db-1.27.0"
      sources."punycode-1.4.1"
      sources."jayschema-0.3.1"
      sources."js-yaml-3.8.3"
      (sources."matrix-appservice-0.3.3" // {
        dependencies = [
          sources."request-2.53.0"
          sources."caseless-0.9.0"
          sources."forever-agent-0.5.2"
          sources."form-data-0.2.0"
          sources."mime-types-2.0.14"
          sources."qs-2.3.3"
          sources."tunnel-agent-0.4.3"
          sources."http-signature-0.10.1"
          sources."oauth-sign-0.6.0"
          sources."hawk-2.3.1"
          sources."aws-sign2-0.5.0"
          sources."combined-stream-0.0.7"
          sources."mime-db-1.12.0"
          sources."assert-plus-0.1.5"
          sources."asn1-0.1.11"
          sources."delayed-stream-0.0.5"
        ];
      })
      (sources."nedb-1.8.0" // {
        dependencies = [
          sources."async-0.2.10"
        ];
      })
      sources."nopt-3.0.6"
      sources."when-3.4.6"
      sources."argparse-1.0.9"
      sources."esprima-3.1.3"
      sources."sprintf-js-1.0.3"
      (sources."body-parser-1.12.4" // {
        dependencies = [
          sources."qs-2.4.2"
        ];
      })
      (sources."express-4.12.4" // {
        dependencies = [
          sources."qs-2.4.2"
        ];
      })
      sources."morgan-1.5.3"
      sources."bytes-1.0.0"
      sources."content-type-1.0.2"
      sources."debug-2.2.0"
      sources."depd-1.0.1"
      sources."iconv-lite-0.4.8"
      sources."on-finished-2.2.1"
      (sources."raw-body-2.0.2" // {
        dependencies = [
          sources."bytes-2.1.0"
        ];
      })
      sources."type-is-1.6.15"
      sources."ms-0.7.1"
      sources."ee-first-1.1.0"
      sources."media-typer-0.3.0"
      sources."accepts-1.2.13"
      sources."content-disposition-0.5.0"
      sources."cookie-0.1.2"
      sources."cookie-signature-1.0.6"
      sources."escape-html-1.0.1"
      sources."etag-1.6.0"
      sources."finalhandler-0.3.6"
      sources."fresh-0.2.4"
      sources."merge-descriptors-1.0.0"
      sources."methods-1.1.2"
      sources."parseurl-1.3.1"
      sources."path-to-regexp-0.1.3"
      sources."proxy-addr-1.0.10"
      sources."range-parser-1.0.3"
      sources."send-0.12.3"
      sources."serve-static-1.9.3"
      sources."vary-1.0.1"
      sources."utils-merge-1.0.0"
      sources."negotiator-0.5.3"
      sources."crc-3.2.1"
      sources."forwarded-0.1.0"
      sources."ipaddr.js-1.0.5"
      sources."destroy-1.0.3"
      sources."mime-1.3.4"
      sources."basic-auth-1.0.4"
      sources."bl-0.9.5"
      sources."node-uuid-1.4.8"
      sources."readable-stream-1.0.34"
      sources."core-util-is-1.0.2"
      sources."isarray-0.0.1"
      sources."string_decoder-0.10.31"
      sources."inherits-2.0.3"
      sources."async-0.9.2"
      sources."ctype-0.5.3"
      sources."browser-request-0.3.3"
      (sources."browserify-10.2.6" // {
        dependencies = [
          sources."readable-stream-1.1.14"
        ];
      })
      sources."q-1.5.0"
      sources."JSONStream-1.3.1"
      sources."assert-1.3.0"
      sources."browser-pack-5.0.1"
      (sources."browser-resolve-1.11.2" // {
        dependencies = [
          sources."resolve-1.1.7"
        ];
      })
      sources."browserify-zlib-0.1.4"
      (sources."buffer-3.6.0" // {
        dependencies = [
          sources."isarray-1.0.0"
        ];
      })
      sources."builtins-0.0.7"
      sources."commondir-0.0.1"
      (sources."concat-stream-1.4.10" // {
        dependencies = [
          sources."readable-stream-1.1.14"
        ];
      })
      sources."console-browserify-1.1.0"
      sources."constants-browserify-0.0.1"
      sources."crypto-browserify-3.11.0"
      sources."defined-1.0.0"
      sources."deps-sort-1.3.9"
      sources."domain-browser-1.1.7"
      (sources."duplexer2-0.0.2" // {
        dependencies = [
          sources."readable-stream-1.1.14"
        ];
      })
      sources."events-1.0.2"
      sources."glob-4.5.3"
      sources."has-1.0.1"
      sources."htmlescape-1.1.1"
      sources."http-browserify-1.7.0"
      sources."https-browserify-0.0.1"
      sources."insert-module-globals-6.6.3"
      sources."labeled-stream-splicer-1.0.2"
      (sources."module-deps-3.9.1" // {
        dependencies = [
          sources."readable-stream-1.1.14"
        ];
      })
      sources."os-browserify-0.1.2"
      sources."parents-1.0.1"
      sources."path-browserify-0.0.0"
      sources."process-0.11.9"
      sources."querystring-es3-0.2.1"
      sources."read-only-stream-1.1.1"
      sources."resolve-1.3.2"
      (sources."shasum-1.0.2" // {
        dependencies = [
          sources."json-stable-stringify-0.0.1"
        ];
      })
      sources."shell-quote-0.0.1"
      sources."stream-browserify-1.0.0"
      sources."subarg-1.0.0"
      sources."syntax-error-1.3.0"
      (sources."through2-1.1.1" // {
        dependencies = [
          sources."readable-stream-1.1.14"
        ];
      })
      sources."timers-browserify-1.4.2"
      sources."tty-browserify-0.0.0"
      (sources."url-0.10.3" // {
        dependencies = [
          sources."punycode-1.3.2"
        ];
      })
      (sources."util-0.10.3" // {
        dependencies = [
          sources."inherits-2.0.1"
        ];
      })
      sources."vm-browserify-0.0.4"
      sources."xtend-4.0.1"
      sources."jsonparse-1.3.0"
      sources."through-2.3.8"
      sources."combine-source-map-0.6.1"
      sources."umd-3.0.1"
      sources."convert-source-map-1.1.3"
      sources."inline-source-map-0.5.0"
      sources."lodash.memoize-3.0.4"
      sources."source-map-0.4.4"
      sources."amdefine-1.0.1"
      sources."pako-0.2.9"
      sources."base64-js-0.0.8"
      sources."ieee754-1.1.8"
      sources."typedarray-0.0.6"
      sources."date-now-0.1.4"
      sources."browserify-cipher-1.0.0"
      sources."browserify-sign-4.0.4"
      sources."create-ecdh-4.0.0"
      sources."create-hash-1.1.2"
      sources."create-hmac-1.1.4"
      sources."diffie-hellman-5.0.2"
      sources."pbkdf2-3.0.9"
      sources."public-encrypt-4.0.0"
      sources."randombytes-2.0.3"
      sources."browserify-aes-1.0.6"
      sources."browserify-des-1.0.0"
      sources."evp_bytestokey-1.0.0"
      sources."buffer-xor-1.0.3"
      sources."cipher-base-1.0.3"
      sources."des.js-1.0.0"
      sources."minimalistic-assert-1.0.0"
      sources."bn.js-4.11.6"
      sources."browserify-rsa-4.0.1"
      sources."elliptic-6.4.0"
      sources."parse-asn1-5.1.0"
      sources."brorand-1.1.0"
      sources."hash.js-1.0.3"
      sources."hmac-drbg-1.0.1"
      sources."minimalistic-crypto-utils-1.0.1"
      sources."asn1.js-4.9.1"
      sources."ripemd160-1.0.1"
      sources."sha.js-2.4.8"
      sources."miller-rabin-4.0.0"
      sources."inflight-1.0.6"
      sources."minimatch-2.0.10"
      sources."once-1.4.0"
      sources."wrappy-1.0.2"
      sources."brace-expansion-1.1.7"
      sources."balanced-match-0.4.2"
      sources."concat-map-0.0.1"
      sources."function-bind-1.1.0"
      sources."Base64-0.2.1"
      sources."is-buffer-1.1.5"
      sources."lexical-scope-1.2.0"
      sources."astw-2.2.0"
      sources."acorn-4.0.11"
      (sources."stream-splicer-1.3.2" // {
        dependencies = [
          sources."readable-stream-1.1.14"
        ];
      })
      (sources."readable-wrap-1.0.0" // {
        dependencies = [
          sources."readable-stream-1.1.14"
        ];
      })
      sources."indexof-0.0.1"
      sources."detective-4.5.0"
      (sources."stream-combiner2-1.0.2" // {
        dependencies = [
          sources."through2-0.5.1"
          sources."xtend-3.0.0"
        ];
      })
      sources."path-platform-0.11.15"
      sources."path-parse-1.0.5"
      sources."querystring-0.2.0"
      sources."binary-search-tree-0.2.5"
      sources."localforage-1.5.0"
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      sources."underscore-1.4.4"
      sources."lie-3.0.2"
      sources."es3ify-0.1.4"
      sources."immediate-3.0.6"
      (sources."inline-process-browser-1.0.0" // {
        dependencies = [
          sources."through2-0.6.5"
        ];
      })
      (sources."unreachable-branch-transform-0.3.0" // {
        dependencies = [
          sources."through2-0.6.5"
        ];
      })
      sources."esprima-fb-3001.1.0-dev-harmony-fb"
      (sources."jstransform-3.0.0" // {
        dependencies = [
          sources."source-map-0.1.31"
        ];
      })
      sources."base62-0.1.1"
      (sources."falafel-1.2.0" // {
        dependencies = [
          sources."acorn-1.2.2"
        ];
      })
      sources."foreach-2.0.5"
      sources."object-keys-1.0.11"
      sources."esmangle-evaluator-1.0.1"
      (sources."recast-0.10.43" // {
        dependencies = [
          sources."esprima-fb-15001.1001.0-dev-harmony-fb"
          sources."source-map-0.5.6"
        ];
      })
      sources."private-0.1.7"
      sources."ast-types-0.8.15"
      sources."abbrev-1.1.0"
      sources."another-json-0.2.0"
      sources."olm-https://matrix.org/packages/npm/olm/olm-1.0.0.tgz"
      sources."array-uniq-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A Matrix <--> Slack bridge";
      homepage = "https://github.com/matrix-org/matrix-appservice-slack#readme";
      license = "Apache-2.0";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}