source 'https://rubygems.org'

gem 'sensu'

# dependencies undeclared but needed by extensions/plugins
gem 'history' # needed by extensions-influxdb

# extensions
gem 'sensu-extensions-check-dependencies'
gem 'sensu-extensions-influxdb2'
gem 'sensu-extensions-snmp-trap'
gem 'sensu-extensions-system-profile'
