source 'https://rubygems.org'

gem 'sensu'

# dependencies undeclared but needed by extensions/plugins
gem 'history' # needed by extensions-influxdb

# forked versions
#
gem 'sensu-plugins-ipmi',           github: 'speartail/sensu-plugins-ipmi',           branch: 'a/driver'
gem 'sensu-plugins-network-checks', github: 'speartail/sensu-plugins-network-checks', branch: 'fixes'

# unreleased fixes
gem 'whois-parser', github: 'weppos/whois-parser', branch: 'master' # OK in 4.0.8+

# integration
gem 'sensu-plugins-aws'        # for the SES handler
gem 'sensu-plugins-mailer'     # now done by sensu-plugins-aws
gem 'sensu-plugins-pushover'

# extensions
gem 'sensu-extensions-check-dependencies'
gem 'sensu-extensions-influxdb2'
gem 'sensu-extensions-snmp-trap'
gem 'sensu-extensions-system-profile'

# checks - cpu and process cannot be installed due to: https://github.com/manveru/bundix/issues/14
# gem 'sensu-plugins-cpu-checks'
# gem 'sensu-plugins-process-checks'
gem 'sensu-plugins-cgroups'
gem 'sensu-plugins-disk-checks'
gem 'sensu-plugins-dns'
gem 'sensu-plugins-http'
gem 'sensu-plugins-influxdb' # checks for influxdb, we do not care about the extension
gem 'sensu-plugins-load-checks'
gem 'sensu-plugins-logs'
gem 'sensu-plugins-raid-checks'
gem 'sensu-plugins-rabbitmq'
gem 'sensu-plugins-redis'
gem 'sensu-plugins-sensu'
gem 'sensu-plugins-sftp'
gem 'sensu-plugins-snmp'
gem 'sensu-plugins-systemd'
gem 'sensu-plugins-uptime-checks'
