# This file has been generated by node2nix 1.1.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
  args = {
    name = "ghetto-skype";
    packageName = "ghetto-skype";
    src = ./.;
    buildInputs = globalBuildInputs;
    meta = {
      homepage = "https://github.com/stanfieldr/ghetto-skype#readme";
      license = "GPL-3.0";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}