# This file has been generated by node2nix 1.2.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "babel-polyfill-6.23.0" = {
      name = "babel-polyfill";
      packageName = "babel-polyfill";
      version = "6.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-polyfill/-/babel-polyfill-6.23.0.tgz";
        sha1 = "8364ca62df8eafb830499f699177466c3b03499d";
      };
    };
    "babel-runtime-6.23.0" = {
      name = "babel-runtime";
      packageName = "babel-runtime";
      version = "6.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.23.0.tgz";
        sha1 = "0a9489f144de70efb3ce4300accdb329e2fc543b";
      };
    };
    "browser-request-0.3.3" = {
      name = "browser-request";
      packageName = "browser-request";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-request/-/browser-request-0.3.3.tgz";
        sha1 = "9ece5b5aca89a29932242e18bf933def9876cc17";
      };
    };
    "classnames-2.2.5" = {
      name = "classnames";
      packageName = "classnames";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/classnames/-/classnames-2.2.5.tgz";
        sha1 = "fb3801d453467649ef3603c7d61a02bd129bde6d";
      };
    };
    "draft-js-0.8.1" = {
      name = "draft-js";
      packageName = "draft-js";
      version = "0.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/draft-js/-/draft-js-0.8.1.tgz";
        sha1 = "484256414c963dd1f5309700ddada10f2aa1f6ff";
      };
    };
    "extract-text-webpack-plugin-0.9.1" = {
      name = "extract-text-webpack-plugin";
      packageName = "extract-text-webpack-plugin";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extract-text-webpack-plugin/-/extract-text-webpack-plugin-0.9.1.tgz";
        sha1 = "ef6dc508cb35ed0dcf8a4009abbe853f7a7622b5";
      };
    };
    "favico.js-0.3.10" = {
      name = "favico.js";
      packageName = "favico.js";
      version = "0.3.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/favico.js/-/favico.js-0.3.10.tgz";
        sha1 = "80586e27a117f24a8d51c18a99bdc714d4339301";
      };
    };
    "filesize-3.5.6" = {
      name = "filesize";
      packageName = "filesize";
      version = "3.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/filesize/-/filesize-3.5.6.tgz";
        sha1 = "5fd98f3eac94ec9516ef8ed5782fad84a01a0a1a";
      };
    };
    "flux-2.0.3" = {
      name = "flux";
      packageName = "flux";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/flux/-/flux-2.0.3.tgz";
        sha1 = "787e1aedffb34a322a60b49c57a2d23856a6de27";
      };
    };
    "gemini-scrollbar-git://github.com/matrix-org/gemini-scrollbar#b302279" = {
      name = "gemini-scrollbar";
      packageName = "gemini-scrollbar";
      version = "1.4.3";
      src = fetchgit {
        url = "git://github.com/matrix-org/gemini-scrollbar";
        rev = "b302279810d05319ac5ff1bd34910bff32325c7b";
        sha256 = "e6a6a16be4001eec57eec6d7597d343be4405809b975cb021e3f0907d2ac4ec1";
      };
    };
    "gfm.css-1.1.1" = {
      name = "gfm.css";
      packageName = "gfm.css";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/gfm.css/-/gfm.css-1.1.1.tgz";
        sha1 = "16b0ef08637f2495b66c84c5024593d71ebeac46";
      };
    };
    "highlight.js-9.10.0" = {
      name = "highlight.js";
      packageName = "highlight.js";
      version = "9.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/highlight.js/-/highlight.js-9.10.0.tgz";
        sha1 = "f9f0b14c0be00f0e4fb1e577b749fed9e6f52f55";
      };
    };
    "linkifyjs-2.1.4" = {
      name = "linkifyjs";
      packageName = "linkifyjs";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkifyjs/-/linkifyjs-2.1.4.tgz";
        sha1 = "b04aac3f327afc871deb205546f612d80bd784b5";
      };
    };
    "matrix-js-sdk-0.7.6" = {
      name = "matrix-js-sdk";
      packageName = "matrix-js-sdk";
      version = "0.7.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/matrix-js-sdk/-/matrix-js-sdk-0.7.6.tgz";
        sha1 = "8039629e3ba070dc23f798f4fec4e79ad42ed24d";
      };
    };
    "matrix-react-sdk-0.8.7" = {
      name = "matrix-react-sdk";
      packageName = "matrix-react-sdk";
      version = "0.8.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/matrix-react-sdk/-/matrix-react-sdk-0.8.7.tgz";
        sha1 = "a930457494082de4235425f16edeb9605ab12915";
      };
    };
    "modernizr-3.5.0" = {
      name = "modernizr";
      packageName = "modernizr";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/modernizr/-/modernizr-3.5.0.tgz";
        sha1 = "396a02231bdc54628bbde2c0813a8e884c7e8060";
      };
    };
    "q-1.5.0" = {
      name = "q";
      packageName = "q";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/q/-/q-1.5.0.tgz";
        sha1 = "dd01bac9d06d30e6f219aecb8253ee9ebdc308f1";
      };
    };
    "react-15.5.4" = {
      name = "react";
      packageName = "react";
      version = "15.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-15.5.4.tgz";
        sha1 = "fa83eb01506ab237cdc1c8c3b1cea8de012bf047";
      };
    };
    "react-dnd-2.3.0" = {
      name = "react-dnd";
      packageName = "react-dnd";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dnd/-/react-dnd-2.3.0.tgz";
        sha1 = "aede61c06b968554dcf2a2445657cdbb3100be49";
      };
    };
    "react-dnd-html5-backend-2.3.0" = {
      name = "react-dnd-html5-backend";
      packageName = "react-dnd-html5-backend";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dnd-html5-backend/-/react-dnd-html5-backend-2.3.0.tgz";
        sha1 = "a45ce593f5c6944aa01114b368117c56c954804e";
      };
    };
    "react-dom-15.5.4" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "15.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-15.5.4.tgz";
        sha1 = "ba0c28786fd52ed7e4f2135fe0288d462aef93da";
      };
    };
    "react-gemini-scrollbar-git://github.com/matrix-org/react-gemini-scrollbar#5e97aef" = {
      name = "react-gemini-scrollbar";
      packageName = "react-gemini-scrollbar";
      version = "2.1.5";
      src = fetchgit {
        url = "git://github.com/matrix-org/react-gemini-scrollbar";
        rev = "5e97aef7e034efc8db1431f4b0efe3b26e249ae9";
        sha256 = "6760f62ca3483009d6ef2f00cc5af88e4537b3c5ad5d6a8caf37b912f83c7f3c";
      };
    };
    "sanitize-html-1.14.1" = {
      name = "sanitize-html";
      packageName = "sanitize-html";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sanitize-html/-/sanitize-html-1.14.1.tgz";
        sha1 = "730ffa2249bdf18333effe45b286173c9c5ad0b8";
      };
    };
    "ua-parser-js-0.7.12" = {
      name = "ua-parser-js";
      packageName = "ua-parser-js";
      version = "0.7.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.12.tgz";
        sha1 = "04c81a99bdd5dc52263ea29d24c6bf8d4818a4bb";
      };
    };
    "url-0.11.0" = {
      name = "url";
      packageName = "url";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url/-/url-0.11.0.tgz";
        sha1 = "3838e97cfc60521eb73c525a8e55bfdd9e2e28f1";
      };
    };
    "core-js-2.4.1" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz";
        sha1 = "4de911e667b0eae9124e34254b53aea6fc618d3e";
      };
    };
    "regenerator-runtime-0.10.3" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.10.3.tgz";
        sha1 = "8c4367a904b51ea62a908ac310bf99ff90a82a3e";
      };
    };
    "fbjs-0.8.12" = {
      name = "fbjs";
      packageName = "fbjs";
      version = "0.8.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/fbjs/-/fbjs-0.8.12.tgz";
        sha1 = "10b5d92f76d45575fd63a217d4ea02bea2f8ed04";
      };
    };
    "immutable-3.7.6" = {
      name = "immutable";
      packageName = "immutable";
      version = "3.7.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-3.7.6.tgz";
        sha1 = "13b4d3cb12befa15482a26fe1b2ebae640071e4b";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "core-js-1.2.7" = {
      name = "core-js";
      packageName = "core-js";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-1.2.7.tgz";
        sha1 = "652294c14651db28fa93bd2d5ff2983a4f08c636";
      };
    };
    "isomorphic-fetch-2.2.1" = {
      name = "isomorphic-fetch";
      packageName = "isomorphic-fetch";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-fetch/-/isomorphic-fetch-2.2.1.tgz";
        sha1 = "611ae1acf14f5e81f729507472819fe9733558a9";
      };
    };
    "loose-envify-1.3.1" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.3.1.tgz";
        sha1 = "d1a8ad33fa9ce0e713d65fdd0ac8b748d478c848";
      };
    };
    "promise-7.1.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.1.1.tgz";
        sha1 = "489654c692616b8aa55b0724fa809bb7db49c5bf";
      };
    };
    "setimmediate-1.0.5" = {
      name = "setimmediate";
      packageName = "setimmediate";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/setimmediate/-/setimmediate-1.0.5.tgz";
        sha1 = "290cbb232e306942d7d7ea9b83732ab7856f8285";
      };
    };
    "node-fetch-1.6.3" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "1.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-1.6.3.tgz";
        sha1 = "dc234edd6489982d58e8f0db4f695029abcd8c04";
      };
    };
    "whatwg-fetch-2.0.3" = {
      name = "whatwg-fetch";
      packageName = "whatwg-fetch";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-fetch/-/whatwg-fetch-2.0.3.tgz";
        sha1 = "9c84ec2dcf68187ff00bc64e1274b442176e1c84";
      };
    };
    "encoding-0.1.12" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.12.tgz";
        sha1 = "538b66f3ee62cd1ab51ec323829d1f9480c74beb";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "iconv-lite-0.4.15" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.15.tgz";
        sha1 = "fe265a218ac6a57cfe854927e9d04c19825eddeb";
      };
    };
    "js-tokens-3.0.1" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-3.0.1.tgz";
        sha1 = "08e9f132484a2c45a30907e9dc4d5567b7f114d7";
      };
    };
    "asap-2.0.5" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.5.tgz";
        sha1 = "522765b50c3510490e52d7dcfe085ef9ba96958f";
      };
    };
    "async-1.5.2" = {
      name = "async";
      packageName = "async";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.5.2.tgz";
        sha1 = "ec6a61ae56480c0c3cb241c95618e20892f9672a";
      };
    };
    "loader-utils-0.2.17" = {
      name = "loader-utils";
      packageName = "loader-utils";
      version = "0.2.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/loader-utils/-/loader-utils-0.2.17.tgz";
        sha1 = "f86e6374d43205a6e6c60e9196f17c0299bfb348";
      };
    };
    "big.js-3.1.3" = {
      name = "big.js";
      packageName = "big.js";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/big.js/-/big.js-3.1.3.tgz";
        sha1 = "4cada2193652eb3ca9ec8e55c9015669c9806978";
      };
    };
    "emojis-list-2.1.0" = {
      name = "emojis-list";
      packageName = "emojis-list";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emojis-list/-/emojis-list-2.1.0.tgz";
        sha1 = "4daa4d9db00f9819880c79fa457ae5b09a1fd389";
      };
    };
    "json5-0.5.1" = {
      name = "json5";
      packageName = "json5";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-0.5.1.tgz";
        sha1 = "1eade7acc012034ad84e2396767ead9fa5495821";
      };
    };
    "jquery-3.2.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.2.1.tgz";
        sha1 = "5c4d9de652af6cd0a770154a631bba12b015c787";
      };
    };
    "another-json-0.2.0" = {
      name = "another-json";
      packageName = "another-json";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/another-json/-/another-json-0.2.0.tgz";
        sha1 = "b5f4019c973b6dd5c6506a2d93469cb6d32aeedc";
      };
    };
    "request-2.81.0" = {
      name = "request";
      packageName = "request";
      version = "2.81.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.81.0.tgz";
        sha1 = "c6928946a0e06c5f8d6f8a9333469ffda46298a0";
      };
    };
    "olm-https://matrix.org/packages/npm/olm/olm-2.2.1.tgz" = {
      name = "olm";
      packageName = "olm";
      version = "2.2.1";
      src = fetchurl {
        name = "olm-2.2.1.tar.gz";
        url = https://matrix.org/packages/npm/olm/olm-2.2.1.tgz;
        sha256 = "70008e0ee2cb024d5f94f0b9eb80f3a72a6c2a90e80aa48212c5be7d06a5e676";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "aws4-1.6.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz";
        sha1 = "83ef5ca860b2b32e4a0deedee8c771b9db57471e";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "extend-3.0.0" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.0.tgz";
        sha1 = "5a474353b9f3353ddd8176dfd37b91c83a46f1d4";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.1.4" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.1.4.tgz";
        sha1 = "33c183acf193276ecaa98143a69e94bfee1750d1";
      };
    };
    "har-validator-4.2.1" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-4.2.1.tgz";
        sha1 = "33481d0f1bbff600dd203d75812a6a5fba002e2a";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "http-signature-1.1.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz";
        sha1 = "df72e267066cd0ac67fb76adf8e134a8fbcf91bf";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "mime-types-2.1.15" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.15.tgz";
        sha1 = "a4ebf5064094569237b8cf70046776d09fc92aed";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "performance-now-0.2.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-0.2.0.tgz";
        sha1 = "33ef30c5c77d4ea21c5a53869d91b56d8f2555e5";
      };
    };
    "qs-6.4.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.4.0.tgz";
        sha1 = "13e26d28ad6b0ffaa91312cd3bf708ed351e7233";
      };
    };
    "safe-buffer-5.0.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.0.1.tgz";
        sha1 = "d263ca54696cd8a306b5ca6551e92de57918fbe7";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.2" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.2.tgz";
        sha1 = "f081f76e4c85720e6c37a5faced737150d84072a";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "uuid-3.0.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.0.1.tgz";
        sha1 = "6544bba2dfda8c1cf17e629a3a305e2bb1fee6c1";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "ajv-4.11.6" = {
      name = "ajv";
      packageName = "ajv";
      version = "4.11.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-4.11.6.tgz";
        sha1 = "947e93049790942b2a2d60a8289b28924d39f987";
      };
    };
    "har-schema-1.0.5" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-1.0.5.tgz";
        sha1 = "d263135f43307c02c602afc8fe95970c0151369e";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "json-stable-stringify-1.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-1.0.1.tgz";
        sha1 = "9a759d39c5f2ff503fd5300646ed445f88c4f9af";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "assert-plus-0.2.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.2.0.tgz";
        sha1 = "d74e1b87e7affc0db8aadb7021f3fe48101ab234";
      };
    };
    "jsprim-1.4.0" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.0.tgz";
        sha1 = "a3b87e40298d8c380552d8cc7628a0bb95a22918";
      };
    };
    "sshpk-1.13.0" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.13.0.tgz";
        sha1 = "ff2a3e4fd04497555fed97b39a0fd82fafb3a33c";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "extsprintf-1.0.2" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.0.2.tgz";
        sha1 = "e1080e0658e300b06294990cc70e1502235fd550";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "verror-1.3.6" = {
      name = "verror";
      packageName = "verror";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.3.6.tgz";
        sha1 = "cff5df12946d297d2baaefaa2689e25be01c005c";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "getpass-0.1.6" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.6.tgz";
        sha1 = "283ffd9fc1256840875311c1b60e8c40187110e6";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "jodid25519-1.0.2" = {
      name = "jodid25519";
      packageName = "jodid25519";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jodid25519/-/jodid25519-1.0.2.tgz";
        sha1 = "06d4912255093419477d425633606e0e90782967";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "mime-db-1.27.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.27.0.tgz";
        sha1 = "820f572296bbd20ec25ed55e5b5de869e5436eb1";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "blueimp-canvas-to-blob-3.7.0" = {
      name = "blueimp-canvas-to-blob";
      packageName = "blueimp-canvas-to-blob";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/blueimp-canvas-to-blob/-/blueimp-canvas-to-blob-3.7.0.tgz";
        sha1 = "6e985b935c0223410c3a2ad96c0ba3ea214c2b13";
      };
    };
    "browser-encrypt-attachment-0.3.0" = {
      name = "browser-encrypt-attachment";
      packageName = "browser-encrypt-attachment";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-encrypt-attachment/-/browser-encrypt-attachment-0.3.0.tgz";
        sha1 = "205a94caadf0dc7e81413941812f655bd190ff1c";
      };
    };
    "commonmark-0.27.0" = {
      name = "commonmark";
      packageName = "commonmark";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commonmark/-/commonmark-0.27.0.tgz";
        sha1 = "d86c262b962821e9483c69c547bc58840c047b34";
      };
    };
    "draft-js-export-html-0.5.2" = {
      name = "draft-js-export-html";
      packageName = "draft-js-export-html";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/draft-js-export-html/-/draft-js-export-html-0.5.2.tgz";
        sha1 = "089e55ce06d5aed0dbd9af5eee2eb56c58a1c428";
      };
    };
    "draft-js-export-markdown-0.2.2" = {
      name = "draft-js-export-markdown";
      packageName = "draft-js-export-markdown";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/draft-js-export-markdown/-/draft-js-export-markdown-0.2.2.tgz";
        sha1 = "5b0a1a10591d8b96199dcb70b04b1ab7deb72a33";
      };
    };
    "emojione-2.2.3" = {
      name = "emojione";
      packageName = "emojione";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/emojione/-/emojione-2.2.3.tgz";
        sha1 = "04383203bf51e6a6c00f1fbddc3309e9543ce78f";
      };
    };
    "file-saver-1.3.3" = {
      name = "file-saver";
      packageName = "file-saver";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-saver/-/file-saver-1.3.3.tgz";
        sha1 = "cdd4c44d3aa264eac2f68ec165bc791c34af1232";
      };
    };
    "fuse.js-2.6.2" = {
      name = "fuse.js";
      packageName = "fuse.js";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fuse.js/-/fuse.js-2.6.2.tgz";
        sha1 = "d5d994fda96f543b5a51df38b72cec9cc60d9dea";
      };
    };
    "glob-5.0.15" = {
      name = "glob";
      packageName = "glob";
      version = "5.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-5.0.15.tgz";
        sha1 = "1bc936b9e02f4a603fcc222ecf7633d30b8b93b1";
      };
    };
    "highlight.js-8.9.1" = {
      name = "highlight.js";
      packageName = "highlight.js";
      version = "8.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/highlight.js/-/highlight.js-8.9.1.tgz";
        sha1 = "b8a9c5493212a9392f0222b649c9611497ebfb88";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "optimist-0.6.1" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz";
        sha1 = "da3ea74686fa21a19a111c326e90eb15a0196686";
      };
    };
    "react-addons-css-transition-group-15.3.2" = {
      name = "react-addons-css-transition-group";
      packageName = "react-addons-css-transition-group";
      version = "15.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-addons-css-transition-group/-/react-addons-css-transition-group-15.3.2.tgz";
        sha1 = "d8fa52bec9bb61bdfde8b9e4652b80297cbff667";
      };
    };
    "text-encoding-utf-8-1.0.1" = {
      name = "text-encoding-utf-8";
      packageName = "text-encoding-utf-8";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-encoding-utf-8/-/text-encoding-utf-8-1.0.1.tgz";
        sha1 = "51ea6c7a7eb2fb4f67467b763735661f5603492d";
      };
    };
    "velocity-vector-git://github.com/vector-im/velocity#059e3b2" = {
      name = "velocity-vector";
      packageName = "velocity-vector";
      version = "1.2.3";
      src = fetchgit {
        url = "git://github.com/vector-im/velocity";
        rev = "059e3b2348f1110888d033974d3109fd5a3af00f";
        sha256 = "c56faf7e9a78627cdd2915b5bebf081509ad424bf0464e475adc499fa5109b1d";
      };
    };
    "whatwg-fetch-1.1.1" = {
      name = "whatwg-fetch";
      packageName = "whatwg-fetch";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-fetch/-/whatwg-fetch-1.1.1.tgz";
        sha1 = "ac3c9d39f320c6dce5339969d054ef43dd333319";
      };
    };
    "entities-1.1.1" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.1.tgz";
        sha1 = "6e5c2d0a5621b5dadaecef80b90edfb5cd7772f0";
      };
    };
    "mdurl-1.0.1" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-1.0.1.tgz";
        sha1 = "fe85b2ec75a59037f2adfec100fd6c601761152e";
      };
    };
    "string.prototype.repeat-0.2.0" = {
      name = "string.prototype.repeat";
      packageName = "string.prototype.repeat";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.repeat/-/string.prototype.repeat-0.2.0.tgz";
        sha1 = "aba36de08dcee6a5a337d49b2ea1da1b28fc0ecf";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "draft-js-utils-0.1.7" = {
      name = "draft-js-utils";
      packageName = "draft-js-utils";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/draft-js-utils/-/draft-js-utils-0.1.7.tgz";
        sha1 = "e2b6927ca620edf1855a4bfc1cf1d21080a70f16";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "minimatch-3.0.3" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.3.tgz";
        sha1 = "2a4e4090b96b2db06a9d7df01055a62a77c9b774";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.7" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.7.tgz";
        sha1 = "3effc3c50e000531fb720eaff80f0ae8ef23cf59";
      };
    };
    "balanced-match-0.4.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz";
        sha1 = "cb3f3e3c732dc0f01ee70b403f302e61d7709838";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "minimist-0.0.10" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz";
        sha1 = "de3f98543dbf96082be48ad1a0c7cda836301dcf";
      };
    };
    "doctrine-1.2.3" = {
      name = "doctrine";
      packageName = "doctrine";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctrine/-/doctrine-1.2.3.tgz";
        sha1 = "6aec6bbd62cf89dd498cae70c0ed9f49da873a6a";
      };
    };
    "file-0.2.2" = {
      name = "file";
      packageName = "file";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/file/-/file-0.2.2.tgz";
        sha1 = "c3dfd8f8cf3535ae455c2b423c2e52635d76b4d3";
      };
    };
    "find-parent-dir-0.3.0" = {
      name = "find-parent-dir";
      packageName = "find-parent-dir";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-parent-dir/-/find-parent-dir-0.3.0.tgz";
        sha1 = "33c44b429ab2b2f0646299c5f9f718f376ff8d54";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "remarkable-1.7.1" = {
      name = "remarkable";
      packageName = "remarkable";
      version = "1.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remarkable/-/remarkable-1.7.1.tgz";
        sha1 = "aaca4972100b66a642a63a1021ca4bac1be3bff6";
      };
    };
    "requirejs-2.1.22" = {
      name = "requirejs";
      packageName = "requirejs";
      version = "2.1.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/requirejs/-/requirejs-2.1.22.tgz";
        sha1 = "dd78fd2d34180c0d62c724b5b8aebc0664e0366f";
      };
    };
    "yargs-7.0.2" = {
      name = "yargs";
      packageName = "yargs";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-7.0.2.tgz";
        sha1 = "115b97df1321823e8b8648e8968c782521221f67";
      };
    };
    "esutils-2.0.2" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.2.tgz";
        sha1 = "0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "argparse-0.1.16" = {
      name = "argparse";
      packageName = "argparse";
      version = "0.1.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-0.1.16.tgz";
        sha1 = "cfd01e0fbba3d6caed049fbd758d40f65196f57c";
      };
    };
    "autolinker-0.15.3" = {
      name = "autolinker";
      packageName = "autolinker";
      version = "0.15.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/autolinker/-/autolinker-0.15.3.tgz";
        sha1 = "342417d8f2f3461b14cf09088d5edf8791dc9832";
      };
    };
    "underscore-1.7.0" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz";
        sha1 = "6bbaf0877500d36be34ecaa584e0db9fef035209";
      };
    };
    "underscore.string-2.4.0" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.4.0.tgz";
        sha1 = "8cdd8fbac4e2d2ea1e7e2e8097c42f442280f85b";
      };
    };
    "camelcase-3.0.0" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-3.0.0.tgz";
        sha1 = "32fc4b9fcdaf845fcdf7e73bb97cac2261f0ab0a";
      };
    };
    "cliui-3.2.0" = {
      name = "cliui";
      packageName = "cliui";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-3.2.0.tgz";
        sha1 = "120601537a916d29940f934da3b48d585a39213d";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "get-caller-file-1.0.2" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-1.0.2.tgz";
        sha1 = "f702e63127e7e231c160a80c1554acb70d5047e5";
      };
    };
    "os-locale-1.4.0" = {
      name = "os-locale";
      packageName = "os-locale";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-locale/-/os-locale-1.4.0.tgz";
        sha1 = "20f9f17ae29ed345e8bde583b13d2009803c14d9";
      };
    };
    "read-pkg-up-1.0.1" = {
      name = "read-pkg-up";
      packageName = "read-pkg-up";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg-up/-/read-pkg-up-1.0.1.tgz";
        sha1 = "9d63c13276c065918d57f002a57f40a1b643fb02";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha1 = "8c64ad5fd30dab1c976e2344ffe7f792a6a6df42";
      };
    };
    "require-main-filename-1.0.1" = {
      name = "require-main-filename";
      packageName = "require-main-filename";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-main-filename/-/require-main-filename-1.0.1.tgz";
        sha1 = "97f717b69d48784f5f526a6c5aa8ffdda055a4d1";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "which-module-1.0.0" = {
      name = "which-module";
      packageName = "which-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-module/-/which-module-1.0.0.tgz";
        sha1 = "bba63ca861948994ff307736089e3b96026c2a4f";
      };
    };
    "y18n-3.2.1" = {
      name = "y18n";
      packageName = "y18n";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-3.2.1.tgz";
        sha1 = "6d15fba884c08679c0d77e88e7759e811e07fa41";
      };
    };
    "yargs-parser-5.0.0" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-5.0.0.tgz";
        sha1 = "275ecf0d7ffe05c77e64e7c86e4cd94bf0e1228a";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "wrap-ansi-2.1.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-2.1.0.tgz";
        sha1 = "d8fc3d284dd05794fe84973caecdd1cf824fdd85";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "lcid-1.0.0" = {
      name = "lcid";
      packageName = "lcid";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lcid/-/lcid-1.0.0.tgz";
        sha1 = "308accafa0bc483a3867b4b6f2b9506251d1b835";
      };
    };
    "invert-kv-1.0.0" = {
      name = "invert-kv";
      packageName = "invert-kv";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/invert-kv/-/invert-kv-1.0.0.tgz";
        sha1 = "104a8e4aaca6d3d8cd157a8ef8bfab2d7a3ffdb6";
      };
    };
    "find-up-1.1.2" = {
      name = "find-up";
      packageName = "find-up";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-1.1.2.tgz";
        sha1 = "6b2e9822b1a2ce0a60ab64d610eccad53cb24d0f";
      };
    };
    "read-pkg-1.1.0" = {
      name = "read-pkg";
      packageName = "read-pkg";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg/-/read-pkg-1.1.0.tgz";
        sha1 = "f5ffaa5ecd29cb31c0474bca7d756b6bb29e3f28";
      };
    };
    "path-exists-2.1.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-2.1.0.tgz";
        sha1 = "0feb6c64f0fc518d9a754dd5efb62c7022761f4b";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "load-json-file-1.1.0" = {
      name = "load-json-file";
      packageName = "load-json-file";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-json-file/-/load-json-file-1.1.0.tgz";
        sha1 = "956905708d58b4bab4c2261b04f59f31c99374c0";
      };
    };
    "normalize-package-data-2.3.6" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.3.6.tgz";
        sha1 = "498fa420c96401f787402ba21e600def9f981fff";
      };
    };
    "path-type-1.1.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-1.1.0.tgz";
        sha1 = "59c44f7ee491da704da415da5a4070ba4f8fe441";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "parse-json-2.2.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-2.2.0.tgz";
        sha1 = "f480f40434ef80741f8469099f8dea18f55a4dc9";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "strip-bom-2.0.0" = {
      name = "strip-bom";
      packageName = "strip-bom";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-bom/-/strip-bom-2.0.0.tgz";
        sha1 = "6219a85616520491f35788bdbf1447a99c7e6b0e";
      };
    };
    "error-ex-1.3.1" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.1.tgz";
        sha1 = "f855a86ce61adc4e8621c3cda21e7a7612c3a8dc";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-utf8-0.2.1" = {
      name = "is-utf8";
      packageName = "is-utf8";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-utf8/-/is-utf8-0.2.1.tgz";
        sha1 = "4b0da1442104d1b336340e80797e865cf39f7d72";
      };
    };
    "hosted-git-info-2.4.2" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.4.2.tgz";
        sha1 = "0076b9f46a270506ddbaaea56496897460612a67";
      };
    };
    "is-builtin-module-1.0.0" = {
      name = "is-builtin-module";
      packageName = "is-builtin-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-builtin-module/-/is-builtin-module-1.0.0.tgz";
        sha1 = "540572d34f7ac3119f8f76c30cbc1b1e037affbe";
      };
    };
    "semver-5.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz";
        sha1 = "9b2ce5d3de02d17c6012ad326aa6b4d0cf54f94f";
      };
    };
    "validate-npm-package-license-3.0.1" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.1.tgz";
        sha1 = "2804babe712ad3379459acfbe24746ab2c303fbc";
      };
    };
    "builtin-modules-1.1.1" = {
      name = "builtin-modules";
      packageName = "builtin-modules";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-modules/-/builtin-modules-1.1.1.tgz";
        sha1 = "270f076c5a72c02f5b65a47df94c5fe3a278892f";
      };
    };
    "spdx-correct-1.0.2" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-1.0.2.tgz";
        sha1 = "4b3073d933ff51f3912f03ac5519498a4150db40";
      };
    };
    "spdx-expression-parse-1.0.4" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-1.0.4.tgz";
        sha1 = "9bdf2f20e1f40ed447fbe273266191fced51626c";
      };
    };
    "spdx-license-ids-1.2.2" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-1.2.2.tgz";
        sha1 = "c9df7a3424594ade6bd11900d596696dc06bac57";
      };
    };
    "code-point-at-1.1.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.1.0.tgz";
        sha1 = "0d070b4d043a5bea33a2f1a40e2edb3d9a4ccf77";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "prop-types-15.5.8" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.5.8.tgz";
        sha1 = "6b7b2e141083be38c8595aa51fc55775c7199394";
      };
    };
    "disposables-1.0.1" = {
      name = "disposables";
      packageName = "disposables";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/disposables/-/disposables-1.0.1.tgz";
        sha1 = "064727a25b54f502bd82b89aa2dfb8df9f1b39e3";
      };
    };
    "dnd-core-2.3.0" = {
      name = "dnd-core";
      packageName = "dnd-core";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dnd-core/-/dnd-core-2.3.0.tgz";
        sha1 = "f7b29ac37e2c78efe89e911ca5a534f280390450";
      };
    };
    "hoist-non-react-statics-1.2.0" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-1.2.0.tgz";
        sha1 = "aa448cf0986d55cc40773b17174b7dd066cb7cfb";
      };
    };
    "invariant-2.2.2" = {
      name = "invariant";
      packageName = "invariant";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/invariant/-/invariant-2.2.2.tgz";
        sha1 = "9e1f56ac0acdb6bf303306f338be3b204ae60360";
      };
    };
    "redux-3.6.0" = {
      name = "redux";
      packageName = "redux";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux/-/redux-3.6.0.tgz";
        sha1 = "887c2b3d0b9bd86eca2be70571c27654c19e188d";
      };
    };
    "lodash-es-4.17.4" = {
      name = "lodash-es";
      packageName = "lodash-es";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash-es/-/lodash-es-4.17.4.tgz";
        sha1 = "dcc1d7552e150a0640073ba9cb31d70f032950e7";
      };
    };
    "symbol-observable-1.0.4" = {
      name = "symbol-observable";
      packageName = "symbol-observable";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/symbol-observable/-/symbol-observable-1.0.4.tgz";
        sha1 = "29bf615d4aa7121bdd898b22d4b3f9bc4e2aa03d";
      };
    };
    "htmlparser2-3.9.2" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.9.2.tgz";
        sha1 = "1bdf87acca0f3f9e53fa4fcceb0f4b4cbb00b338";
      };
    };
    "regexp-quote-0.0.0" = {
      name = "regexp-quote";
      packageName = "regexp-quote";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp-quote/-/regexp-quote-0.0.0.tgz";
        sha1 = "1e0f4650c862dcbfed54fd42b148e9bb1721fcf2";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "domelementtype-1.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.0.tgz";
        sha1 = "b17aed82e8ab59e52dd9c19b1756e0fc187204c2";
      };
    };
    "domhandler-2.3.0" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.3.0.tgz";
        sha1 = "2de59a0822d5027fabff6f032c2b25a2a8abe738";
      };
    };
    "domutils-1.5.1" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.5.1.tgz";
        sha1 = "dcd8488a26f563d61079e48c9f7b7e32373682cf";
      };
    };
    "readable-stream-2.2.9" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.2.9.tgz";
        sha1 = "cf78ec6f4a6d1eb43d26488cac97f042e74b7fc8";
      };
    };
    "dom-serializer-0.1.0" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.1.0.tgz";
        sha1 = "073c697546ce0780ce23be4a28e293e40bc30c82";
      };
    };
    "domelementtype-1.1.3" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.1.3.tgz";
        sha1 = "bd28773e2642881aec51544924299c5cd822185b";
      };
    };
    "buffer-shims-1.0.0" = {
      name = "buffer-shims";
      packageName = "buffer-shims";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-shims/-/buffer-shims-1.0.0.tgz";
        sha1 = "9978ce317388c649ad8793028c3477ef044a8b51";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-1.0.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.0.tgz";
        sha1 = "f06f41157b664d86069f84bdbdc9b0d8ab281667";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "punycode-1.3.2" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz";
        sha1 = "9653a036fb7c1ee42342f2325cceefea3926c48d";
      };
    };
    "querystring-0.2.0" = {
      name = "querystring";
      packageName = "querystring";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz";
        sha1 = "b209849203bb25df820da756e747005878521620";
      };
    };
  };
  args = {
    name = "riot-web";
    packageName = "riot-web";
    version = "0.9.8";
    src = ./.;
    dependencies = [
      sources."babel-polyfill-6.23.0"
      sources."babel-runtime-6.23.0"
      sources."browser-request-0.3.3"
      sources."classnames-2.2.5"
      sources."draft-js-0.8.1"
      sources."extract-text-webpack-plugin-0.9.1"
      sources."favico.js-0.3.10"
      sources."filesize-3.5.6"
      sources."flux-2.0.3"
      sources."gemini-scrollbar-git://github.com/matrix-org/gemini-scrollbar#b302279"
      sources."gfm.css-1.1.1"
      sources."highlight.js-9.10.0"
      sources."linkifyjs-2.1.4"
      sources."matrix-js-sdk-0.7.6"
      (sources."matrix-react-sdk-0.8.7" // {
        dependencies = [
          sources."highlight.js-8.9.1"
          sources."whatwg-fetch-1.1.1"
        ];
      })
      sources."modernizr-3.5.0"
      sources."q-1.5.0"
      sources."react-15.5.4"
      sources."react-dnd-2.3.0"
      sources."react-dnd-html5-backend-2.3.0"
      sources."react-dom-15.5.4"
      sources."react-gemini-scrollbar-git://github.com/matrix-org/react-gemini-scrollbar#5e97aef"
      sources."sanitize-html-1.14.1"
      sources."ua-parser-js-0.7.12"
      (sources."url-0.11.0" // {
        dependencies = [
          sources."punycode-1.3.2"
        ];
      })
      sources."core-js-2.4.1"
      sources."regenerator-runtime-0.10.3"
      (sources."fbjs-0.8.12" // {
        dependencies = [
          sources."core-js-1.2.7"
        ];
      })
      sources."immutable-3.7.6"
      sources."object-assign-4.1.1"
      sources."isomorphic-fetch-2.2.1"
      sources."loose-envify-1.3.1"
      sources."promise-7.1.1"
      sources."setimmediate-1.0.5"
      sources."node-fetch-1.6.3"
      sources."whatwg-fetch-2.0.3"
      sources."encoding-0.1.12"
      sources."is-stream-1.1.0"
      sources."iconv-lite-0.4.15"
      sources."js-tokens-3.0.1"
      sources."asap-2.0.5"
      sources."async-1.5.2"
      sources."loader-utils-0.2.17"
      sources."big.js-3.1.3"
      sources."emojis-list-2.1.0"
      sources."json5-0.5.1"
      sources."jquery-3.2.1"
      sources."another-json-0.2.0"
      sources."request-2.81.0"
      sources."olm-https://matrix.org/packages/npm/olm/olm-2.2.1.tgz"
      sources."aws-sign2-0.6.0"
      sources."aws4-1.6.0"
      sources."caseless-0.12.0"
      sources."combined-stream-1.0.5"
      sources."extend-3.0.0"
      sources."forever-agent-0.6.1"
      sources."form-data-2.1.4"
      sources."har-validator-4.2.1"
      sources."hawk-3.1.3"
      sources."http-signature-1.1.1"
      sources."is-typedarray-1.0.0"
      sources."isstream-0.1.2"
      sources."json-stringify-safe-5.0.1"
      sources."mime-types-2.1.15"
      sources."oauth-sign-0.8.2"
      sources."performance-now-0.2.0"
      sources."qs-6.4.0"
      sources."safe-buffer-5.0.1"
      sources."stringstream-0.0.5"
      sources."tough-cookie-2.3.2"
      sources."tunnel-agent-0.6.0"
      sources."uuid-3.0.1"
      sources."delayed-stream-1.0.0"
      sources."asynckit-0.4.0"
      sources."ajv-4.11.6"
      sources."har-schema-1.0.5"
      sources."co-4.6.0"
      sources."json-stable-stringify-1.0.1"
      sources."jsonify-0.0.0"
      sources."hoek-2.16.3"
      sources."boom-2.10.1"
      sources."cryptiles-2.0.5"
      sources."sntp-1.0.9"
      sources."assert-plus-0.2.0"
      (sources."jsprim-1.4.0" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      (sources."sshpk-1.13.0" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."extsprintf-1.0.2"
      sources."json-schema-0.2.3"
      sources."verror-1.3.6"
      sources."asn1-0.2.3"
      (sources."dashdash-1.14.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      (sources."getpass-0.1.6" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."jsbn-0.1.1"
      sources."tweetnacl-0.14.5"
      sources."jodid25519-1.0.2"
      sources."ecc-jsbn-0.1.1"
      sources."bcrypt-pbkdf-1.0.1"
      sources."mime-db-1.27.0"
      sources."punycode-1.4.1"
      sources."blueimp-canvas-to-blob-3.7.0"
      sources."browser-encrypt-attachment-0.3.0"
      sources."commonmark-0.27.0"
      sources."draft-js-export-html-0.5.2"
      sources."draft-js-export-markdown-0.2.2"
      sources."emojione-2.2.3"
      sources."file-saver-1.3.3"
      sources."fuse.js-2.6.2"
      sources."glob-5.0.15"
      sources."lodash-4.17.4"
      (sources."optimist-0.6.1" // {
        dependencies = [
          sources."minimist-0.0.10"
        ];
      })
      sources."react-addons-css-transition-group-15.3.2"
      sources."text-encoding-utf-8-1.0.1"
      sources."velocity-vector-git://github.com/vector-im/velocity#059e3b2"
      sources."entities-1.1.1"
      sources."mdurl-1.0.1"
      sources."string.prototype.repeat-0.2.0"
      sources."minimist-1.2.0"
      sources."draft-js-utils-0.1.7"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."minimatch-3.0.3"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."wrappy-1.0.2"
      sources."brace-expansion-1.1.7"
      sources."balanced-match-0.4.2"
      sources."concat-map-0.0.1"
      sources."wordwrap-0.0.3"
      sources."doctrine-1.2.3"
      sources."file-0.2.2"
      sources."find-parent-dir-0.3.0"
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      sources."remarkable-1.7.1"
      sources."requirejs-2.1.22"
      sources."yargs-7.0.2"
      sources."esutils-2.0.2"
      sources."isarray-1.0.0"
      sources."argparse-0.1.16"
      sources."autolinker-0.15.3"
      sources."underscore-1.7.0"
      sources."underscore.string-2.4.0"
      sources."camelcase-3.0.0"
      sources."cliui-3.2.0"
      sources."decamelize-1.2.0"
      sources."get-caller-file-1.0.2"
      sources."os-locale-1.4.0"
      sources."read-pkg-up-1.0.1"
      sources."require-directory-2.1.1"
      sources."require-main-filename-1.0.1"
      sources."set-blocking-2.0.0"
      sources."string-width-1.0.2"
      sources."which-module-1.0.0"
      sources."y18n-3.2.1"
      sources."yargs-parser-5.0.0"
      sources."strip-ansi-3.0.1"
      sources."wrap-ansi-2.1.0"
      sources."ansi-regex-2.1.1"
      sources."lcid-1.0.0"
      sources."invert-kv-1.0.0"
      sources."find-up-1.1.2"
      sources."read-pkg-1.1.0"
      sources."path-exists-2.1.0"
      sources."pinkie-promise-2.0.1"
      sources."pinkie-2.0.4"
      sources."load-json-file-1.1.0"
      sources."normalize-package-data-2.3.6"
      sources."path-type-1.1.0"
      sources."graceful-fs-4.1.11"
      sources."parse-json-2.2.0"
      sources."pify-2.3.0"
      sources."strip-bom-2.0.0"
      sources."error-ex-1.3.1"
      sources."is-arrayish-0.2.1"
      sources."is-utf8-0.2.1"
      sources."hosted-git-info-2.4.2"
      sources."is-builtin-module-1.0.0"
      sources."semver-5.3.0"
      sources."validate-npm-package-license-3.0.1"
      sources."builtin-modules-1.1.1"
      sources."spdx-correct-1.0.2"
      sources."spdx-expression-parse-1.0.4"
      sources."spdx-license-ids-1.2.2"
      sources."code-point-at-1.1.0"
      sources."is-fullwidth-code-point-1.0.0"
      sources."number-is-nan-1.0.1"
      sources."prop-types-15.5.8"
      sources."disposables-1.0.1"
      sources."dnd-core-2.3.0"
      sources."hoist-non-react-statics-1.2.0"
      sources."invariant-2.2.2"
      sources."redux-3.6.0"
      sources."lodash-es-4.17.4"
      sources."symbol-observable-1.0.4"
      sources."htmlparser2-3.9.2"
      sources."regexp-quote-0.0.0"
      sources."xtend-4.0.1"
      sources."domelementtype-1.3.0"
      sources."domhandler-2.3.0"
      sources."domutils-1.5.1"
      sources."readable-stream-2.2.9"
      (sources."dom-serializer-0.1.0" // {
        dependencies = [
          sources."domelementtype-1.1.3"
        ];
      })
      sources."buffer-shims-1.0.0"
      sources."core-util-is-1.0.2"
      sources."process-nextick-args-1.0.7"
      sources."string_decoder-1.0.0"
      sources."util-deprecate-1.0.2"
      sources."querystring-0.2.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A feature-rich client for Matrix.org";
      license = "Apache-2.0";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}